### ISSUE TITLE
deriveLinkedEntries does not support existing linked entries

### ISSUE THREAD

**Issue by chasenyc** [contentful/contentful-migration#1043]
## Expected Behavior

If the linked entry already exists, it should not attempt to create a new entry.

## Actual Behavior

It attempts to create a new entry and fails with `VersionMismatch` error. This is happening because it tries to create a new entry (which passes the header `X-Version: 0`)

## Possible Solution

In  :
```ts
// /src/lib/action/entry-derive.ts

  async applyTo(api: OfflineAPI) {
    const entries: Entry[] = await api.getEntriesForContentType(this.contentTypeId)
    const locales: string[] = await api.getLocalesForSpace()
    const sourceContentType: ContentType = await api.getContentType(this.contentTypeId)

    for (const entry of entries) {
      const inputs = _.pick(entry.fields, this.fromFields)
      const newEntryId = await this.identityKey(inputs)
      const hasEntry = await api.hasEntry(newEntryId)
```

then later the following code:
```ts
// /src/lib/action/entry-derive.ts

      if (!hasEntry) {
        // TODO: How do we handle already existing links?
        // Usually you would not want to derive the contents again
        // But what if the previous round may not have been complete
        // for example one optional field was missing in the previous iteration
        const targetEntry = await api.createEntry(this.derivedContentType, newEntryId)
```
However, if I am reading the code above correctly, entries refers to the original contentType, not the derivedContentType, therefore the `api.hasEntry(newEntryId)` is checking against `this.entries` which I *believe* is an array of the original content model, not the derived content model so it will never come back as true.

## Steps to Reproduce

Use the `examples/15-derive-entry-n-to-1.js` example and associated test(`test/end-to-end/derive-entry-spec.js`), however; change the setup to have owner already exist and have an owner with `Contentful Office` already exist for the owner model.

## Context

I have a model that currently has a string representation of a country on it and want to switch to a linked entry to a country model and I am unable to link to already existing models without exceptions being thrown during migration. The migration itself works as the models already exist; however, the exit status code from the failure to create the models is causing issues with my CI workflow.

```sh
Error: {"status":"Conflict","message":"","details":{},"url":"spaces/6xxxxxxx2/environments/contentful-testing/entries/5xxxxxxxxxf"}
```

## Environment

-   **Node Version**:  v16.13.2
-   **Package Manager Version**: 6.14.15
-   **Operating System**: 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64 (macOS 12.1 M1 Pro AMD)
-   **Package Version**: 4.8.1

**Comment by diegoaguilar** [comment]
@ruderngespra did you find any solution for this?

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.
