### ISSUE TITLE
Creating new type does not update the Shared Views in the UI

### ISSUE THREAD

**Issue by lincetto** [contentful/contentful-migration#1046]
## Expected Behavior

Same behaviour when creating a new content type from UI and migration API

## Actual Behavior

Creating a content type from migration API does not automatically add a new View for the new type under "Content Type" section in Shared Views in the left column of "Content" tab.
We need to "touch" the content model in the UI in order to let this new view link to appear in the left column of "Content" tab.

## Possible Solution

N/A

## Steps to Reproduce

1. Create a new content type from migration api
2. No link under "Shared Views" has been created in the UI for the new type

**Comment by damienxy** [comment]
Hi @lincetto, updating the Shared Views section via the migration directly is currently not supported. 
So the workaround is indeed to touch the content type in the web app to make it appear there.
