### ISSUE TITLE
`deriveEntryForLocale` does not transfer derived entry to correct locale but derives fallback locale entry everywhere

### ISSUE THREAD

**Issue by patibugaj** [contentful/contentful-migration#1057]
## Expected Behavior

I would like to create a new content type (`contentType2`) from the existed field (in `contentType1`), which is `n to n` reference with all the entries. These newly created content type entries (`contentType2`) I would like to use as a single reference in the `contentType2` field.

For example our `contentType1` looks like that:
```
  {
    title,
    image,
    body: [
      reference1,
      reference2
    ],
    ...
  }
```
Field body has translations available. And we have around 10 locales.

Our `contentType2` gets references from a field `body` from `contentType1`. It looks like that:
```
 {
    name,
    body: [
      reference1,
      reference2
    ],
  }
```
Field body has NO translations available (this is a difference with body in `contentType1`)

And now I would like to use `contentType2` as a reference in `contentType1`, so our `contentType1` should look like that:
```
{
  title,
  image,
  newBody: contentType2Reference
}
```

For example, from this kind of entry:
<img width="700" alt="image" src="https://user-images.githubusercontent.com/37595963/163270820-d9ddeb82-678a-4fef-89ea-142b61a6cff2.png">

I would like to have two `contentType2` created - one for `de-DE` and second one for `pl` translation. Next in the `contentType1` I would like to reference `contentType2` de-DE entry to the `newBody` translation `de-DE`, `contentType2` pl entry to the `newBody` translation `pl`, and rest translation for `newBody` leave empty.
![image](https://user-images.githubusercontent.com/37595963/163272361-c8875b6c-a0ad-4a48-8a1f-f768e0bc65b2.png)

## Actual Behavior
I decided to use the `deriveLinkedEntries` method to obtain that transformation. Unfortunately I faced an issue with translations. I have 10 locales in Contentful and the field `body` might be different per locale or it can be empty for a locale. With `deriveLinkedEntries` I was able to create my new `contentType2` for all locales, but only translations for our fallback locale has been created with content, for other locales the content has been empty. Our default locale is `de-DE`. 
Here is an example of `contentType2` created for locale `fr`.
![image](https://user-images.githubusercontent.com/37595963/163268821-09ee0e6e-441f-4996-80ba-14442e4462de.png)
Here is an example of `contentType2` created for default locale `de-DE`.
![image](https://user-images.githubusercontent.com/37595963/163268886-414f8862-d779-443d-88db-8f8418c91d3f.png)

And also references of `contentType2` are wrongly uploaded in `contentType1` for locales. Instead of uploading only references for locales where the field `body` has some content, the reference of fallback locale has been uploaded for all locales.
![image](https://user-images.githubusercontent.com/37595963/163270316-a31d9397-2512-481f-9c2f-53f1d72ec2ec.png)

## Steps to Reproduce
This is my script:
```
function migrationFunction(migration) {
  migration.deriveLinkedEntries({
    contentType: 'globalPage',
    derivedContentType: 'referenceBody',
    from: ['referenceBodyKey', 'body'],
    toReferenceField: 'sections',
    derivedFields: ['name', 'body'],
    identityKey: async fromFields => {
      return fromFields.referenceBodyKey['de-DE'];
    },
    shouldPublish: 'preserve',
    deriveEntryForLocale: async (inputFields, locale) => {
      const referenceBodyName = `${inputFields.referenceBodyKey['de-DE']}-${locale}`;
      if (!inputFields.body) return;
      const referenceBodyBody = inputFields.body[locale];
      if (!referenceBodyBody) return;
      return {
        name: referenceBodyName,
        body: referenceBodyBody,
      };
    },
  });
}
```

Could you tell me if there is a possibility to improve my script? Or if I should use a different method to obtain my goal?

## Environment

-   **Node Version**: 
-   **Package Manager Version**: 
-   **Operating System**: 
-   **Package Version**:

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.
