### ISSUE TITLE
Cannot create validation with assetImageDimension values that are null.

### ISSUE THREAD

**Issue by bkempner** [contentful/contentful-migration#106]
Hello, I have an asset as a field in one of my content models, when I created the validations for it using the website it worked fine and this is the JSON representation it creates: 

```
{
  "assetImageDimensions": {
    "width": {
      "min": 1100,
      "max": null
    },
    "height": {
      "min": null,
      "max": null
    }
  }
}
```

However, if I try to create a migration using this package and I use null as a max or min value then the cli command errors and doesn't allow me to run the migration:

```
Error: "max" validation expected to be "number", but got "null"
Error: "min" validation expected to be "number", but got "null"
Error: "max" validation expected to be "number", but got "null"
```

If I simply omit it the null values like this:

```
{
  assetImageDimensions: {
    width: {
      min: 1100
    }
  }
}
```

Then the migration command runs successfully, but when I use the website I cannot edit the field, if I try I get an error "The application has encountered a problem and needs to reload".  I am speculating that this is because of the missing height/width or max/min values, the website needs them to be `null`, however I don't think it's entirely a problem with the website because clearly `null` values are allowed and the cli command erroneously prevents them from being specified.

**Comment by jordanrastrick** [comment]
I'm seeing the same problems with `null` `max`/`min` values that work in a live space causing errors when running a migration (using v0.14.2 of `contentful-cli`). Was this closed because a fix has been implemented, and if so what is required to apply it? Cheers.

**Comment by phoebeschmidt** [comment]
We realized this is an issue with our validations in this tool, not the webapp. Working on a fix now, probably to be released next week.

**Comment by phoebeschmidt** [comment]
We expect to release a new version tomorrow which will include this fix. I'll comment again when it's live.
