### ISSUE TITLE
ContentType.resetEntryEditor not available in type definitions

### ISSUE THREAD

**Issue by gigaSproule** [contentful/contentful-migration#1093]
## Expected Behavior
ContentType should have the type definition for `resetEntryEditor` as per https://github.com/contentful/contentful-migration/blob/master/src/lib/migration-steps/index.ts#L452.

## Actual Behavior
Get the typescript error "Property 'resetEntryEditor' does not exist on type 'ContentType'.ts(2339)".

## Possible Solution
Add type information for function.

## Steps to Reproduce
1. Create a migration script which creates or edits a `ContentType`
2. Call `resetEntryEeditor` on that `ContentType` reference
3. Try to compile with `tsc`

## Environment
-   **Node Version**: v14.19.3
-   **Package Manager Version**: yarn 1.18.0
-   **Operating System**: Arch Linux
-   **Package Version**: 4.8.1

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.
