### ISSUE TITLE
Which library to use for Contentful migration as a library

### ISSUE THREAD

**Issue by benjarwar** [contentful/contentful-migration#110]
I'm unclear about the documentation regarding using the [migration CLI tool as a library](https://github.com/contentful/contentful-migration#usage-as-a-library). The README example indicates we should import like so, from `contentful-migration`:

```
const runMigration = require('contentful-migration/built/bin/cli')
```

Is this still the case, or should we be importing from a version in the main [Contentful CLI](https://github.com/contentful/contentful-cli) project?

**Comment by Khaledgarbaya** [comment]
Hey @benjarwar,
yes, that's right you can import the library in your code like that.
the contentful-cli is not meant to use as a library
Best,
Khaled
