### ISSUE TITLE
Versioning migrations

### ISSUE THREAD

**Issue by ioanac95** [contentful/contentful-migration#1105]
## Context

We are using this library to manage the changes in our content model. Since our space contains multiple environments which we are using for dev, staging, prod the content model can be at different versions in each of them. 

Right now, if we want to migrate the content types, we need to manually identify which version we are currently at in the environment that we are migrating and then apply the appropriate migration files. It would be very helpful to be able to have a way of automatically detecting the version that the content is currently at and upgrading to the next one, like we can do in other ORM tools. Is this enhancement on your radar to implement in the near future?

If not, how do you recommend solving this issue?

## Expected Behavior - potential solution

- Define migration file for version `1` of the content model
- Have a way to store version information in the content model. After migration `1` is applied, save the value `1` in the content, together with the date it was migrated
- Define migration file for version `2` of the content model
- When we tell the script to migrate to version 2, if the content does not have version information then both migrations 1 and 2 will be applied. Otherwise, if the content is at version 1, only migration 2 will be applied. If the content is up to date to version 2, no migration will be applied
- After migration `2` is applied, store another entry that tells us the date of the migration and the version (`2`)

## Environment

-   **Node Version**: v16.13.0
-   **Package Manager Version**: 8.1.0
-   **Operating System**: macOS Big Sur (version 11.6.7)
-   **Package Version**: v4.9.0

**Comment by marcolink** [comment]
Hi @ioanac95,
Thanks for your request. 

We currently do not support migration versioning, but there are great 3rd party tools. 

To name some: 
- https://github.com/rouanw/umzug-contentful
- https://github.com/watermarkchurch/contentful-migration

In the meantime, feel free to re-open the issue with any additional details.

Best
Marco
