### ISSUE TITLE
Catching errors or aborted runs when using migration CLI as a library

### ISSUE THREAD

**Issue by benjarwar** [contentful/contentful-migration#111]
## Expected Behavior

When use the CLI tool as a library and running a migration, I need to catch both:

1. When a migration fails
2. When the user hits `n` when prompted to proceed with the migration

## Actual Behavior

The function currently does not throw an error or return a Promise that would allow me to catch these cases. Therefore, when I run a migration via my Node scripts, subsequent code that should only run on successful migration is running every time.

## Possible Solution

The returns should for each case could perhaps be improved:

- Success [currently returns the results of Listr.run()](https://github.com/contentful/contentful-migration/blob/master/src/bin/cli.ts#L169) which in my testing is an empty `{}` Object. This object could be enhanced to provide a mechanism for checking results.
- The [error catch](https://github.com/contentful/contentful-migration/blob/master/src/bin/cli.ts#L175) doesn't return anything.
- The [migration aborted](https://github.com/contentful/contentful-migration/blob/master/src/bin/cli.ts#L178) condition doesn't return anything.

## Steps to Reproduce

Stripped down code:

```
const cfRunMigration = require("contentful-migration/built/bin/cli").default;

const runMigration = async () => {
  try {
    const options = {
      // redacted
    };

    await cfRunMigration(options);
  } catch (e) {
    // doesn't seem to fire on errors, because no error is thrown by cfRunMigration
    console.log(e);
  }

  // Always runs, even on error or when migration is aborted
  thisShouldNotAlwaysRun();
}
```

I can sort of solve for the aborted attempts by checking if the output of `cfRunMigration` is undefined; but that feels dirty:

```
const cfRunMigration = require("contentful-migration/built/bin/cli").default;

const runMigration = async () => {
  let migrationResult;

  try {
    const options = {
      // redacted
    };

    migrationResult = await cfRunMigration(options);
  } catch (e) {
    // doesn't seem to fire on errors, because no error is thrown by cfRunMigration
    console.log(e);
  }

  // Dirty check
  if (typeof migrationResult !== 'undefined') {
    thisShouldNotAlwaysRun();
  }
}
```

## Context

I am trying to create a process and automated scripts for running migrations against multiple environments on our CI. Our plan is, when running a migration script file, we will persist the file name to the target space/environment as a record, and a mechanism against attempting to re-run the migration file later. We have need to check that a migration has been truly, successfully run (both on our CI and during local development), before persisting the filename to the space/environment. Currently, that's tricky because of the lack of proper returns for error/aborted attempt cases.

## Environment

-   **Node Version**: v8.9.4
-   **Package Manager Version**: v6.1.0
-   **Operating System**: Mac OSX 10.13.5
-   **Package Version**: v0.9.0

**Comment by charlespwd** [comment]
I believe this issue is fixed @benjarwar @Khaledgarbaya

**Comment by Khaledgarbaya** [comment]
This issue was fixed in the latest release
