### ISSUE TITLE
derivedLinkedEntries should throw if the entity key doesn't match the resourceId regular expression

### ISSUE THREAD

**Issue by charlespwd** [contentful/contentful-migration#115]
## Expected Behavior

Creating entries with commas, spaces or illegal characters should throw.

## Actual Behavior

Creating entries with commas, spaces, or illegal characters in the identity key is allowed. 

## Possible Solution

Verify the identity key with `/^[a-zA-Z0-9\.-_]{1,64}$/` before creating.

## Steps to Reproduce

1.

```js

module.exports = function(migration) {
  migration.deriveLinkedEntries({
    contentType: 'dog',
    derivedContentType: 'owner',
    from: ['owner'],
    toReferenceField: 'ownerRef',
    derivedFields: ['firstName', 'lastName'],
    identityKey: (fields) => {
      const [firstName, lastName] = fields.owner.split(' ');
      return `${lastName}, ${firstName}`
    },
    deriveEntryForLocale: async (fields, locale) => {
      /* ... */
    },
  });
};
```

## Context

I was running a migration and the links were failing. 

## Environment

-   **Node Version**: 8.9.4
-   **Package Manager Version**: 5.6.0
-   **Operating System**: Linux  4.17.3-1-ARCH #1 SMP PREEMPT Tue Jun 26 04:42:36 UTC 2018 x86_64 GNU/Linux

-   **Package Version**: 0.9.0

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.
