### ISSUE TITLE
Token/SpaceId not exists even if they are

### ISSUE THREAD

**Issue by stefanzmindit** [contentful/contentful-migration#117]
## Expected Behavior

Run a contentful migration
## Actual Behavior

Not able to run contentful migrations (most basic one*), getting this error 
_The provided space does not exist or you do not have access_. Removing contentful-migration@**0.10.0** and switching back to **0.9.0** works as expected using the same spaceId and accessToken

*migration example:
```
module.exports = function(migration) {
    migration.createContentType('test', {
        'name': 'Test',
        'description': 'Test'
    });
}
```

## Environment

-   **Node Version**: v10.0.0
-   **Package Manager Version**: 5.6.0
-   **Operating System**: Darwin Mindits-MacBook-Pro.local 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64
-   **Package Version**: 0.10.0

**Comment by Khaledgarbaya** [comment]
Hey @stefanzmindit are you using the tool as a library or as the command line. Can you provide the usage snippet

**Comment by stefanzmindit** [comment]
Hey,

I use it as library through a node script:

```
const runMigration = require('contentful-migration/built/bin/cli').default
const pathJoin = require('path').join;

function migrate() {
    runMigration({
        spaceId: 'SPACEID',
        accessToken: 'TOKEN',
        filePath: pathJoin(__dirname, 'files/migrate_1.js')
    })
        .then(() => console.log('Migration Done!'))
        .catch((e) => console.error)        
}

migrate();
```

and in files/migrate_1.js

```
module.exports = function(migration) {
    migration.createContentType('test', {
        'name': 'Test',
        'description': 'Test'
    });
}
```

package.json looks like

```
{
  "name": "migration",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "migrate": "node do.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "contentful": "^6.1.1",
    "contentful-migration": "^0.9.0"
  }
}
```

**Comment by stefanzmindit** [comment]
Running the same script ```node run migrate``` with 0.10.0 gives me the error described, but replacing it with 0.9.0 (without doing anything else than npm uninstall contentful-migration and npm install contentful-migration@0.9.0) works fine

**Comment by stefanjudis** [comment]
@stefanzmindit It might be that I know what's the problem. Can you confirm that the same script with the [contentful-cli](https://github.com/contentful/contentful-cli/tree/master/docs/space/migration) works as expected?

**Comment by stefanzmindit** [comment]
I have run (after login)
```contentful space migration --space-id SPACEID files/migrate_1.js``` and works as expected  (Migration successful and running one more time - Line 2: Content type with id "test" already exists.)

contentful -v : 0.14.2

*the same SPACEID used in the script/example above

**Comment by Khaledgarbaya** [comment]
Hey @stefanzmindit,
Can you try this code ?

```js
const runMigration = require('contentful-migration/built/bin/cli').default
const pathJoin = require('path').join;

function migrate() {
    runMigration({
        spaceId: 'SPACEID',
        environmentId: 'master',
        accessToken: 'TOKEN',
        filePath: pathJoin(__dirname, 'files/migrate_1.js')
    })
        .then(() => console.log('Migration Done!'))
        .catch((e) => console.error)        
}

migrate();
``` 
I will work on a fix today and release it

**Comment by stefanzmindit** [comment]
Magic, adding environmentId works :D.
