### ISSUE TITLE
The provided space does not exist or you do not have access.

### ISSUE THREAD

**Issue by nicco91** [contentful/contentful-migration#121]
## Expected Behavior

Run a migration js script with node

`$ node ./migrate.js`

I expected to ask a confirmation to run the migration.

## Actual Behavior

The script tells me the space does not exists:

```
{ makeRequest: [Function: makeRequest],
  application: 'contentful.migration-cli/0.10.0',
  accessToken: <accessToken>,
  spaceId: <spaceId>,
  environmentId: 'develop' }
The provided space does not exist or you do not have access.

🚨  Migration unsuccessful
```

The object you see is the log of the context.
Anyway, I can definitely confirm that the space exists, I used it before in both environments (master, develop). I tried also hardcoding "master" environmentId, but does not work anyway.

## Steps to Reproduce

Here is my scripts:

- **migrate.js**

```
const runMigration = require('contentful-migration/built/bin/cli').default;
const pathJoin = require('path').join;
const options = require('./config/tcom/config.test.json');

function migrate() {
  runMigration({
    spaceId: options['space-id'],
    environmentId: options['environment-id'],
    accessToken: options['access-token'],
    filePath: pathJoin(__dirname, 'migrations/3.13.0.js')
  })
    .then(() => console.log('Migration Done!'))
    .catch((e) => console.error(e));
}

migrate();
```

- **migrations/3.13.0.js**

```
module.exports = async function (migration, context) {
  const pack = migration.editContentType('pack');

  pack.createField('servicesDescription', {
    name: 'Services Description',
    type: 'Text'
  });

  console.log(context);
};
```

## Environment

-   **Node Version**: 8.11.3
-   **Package Manager Version**: 5.6.0
-   **Operating System**: Windows 10 64-bit
-   **Package Version**: contentful-migration v0.10.0

**Comment by Khaledgarbaya** [comment]
Hey @nicco91,
is the environment `develop` created? did you make sure that accessToken is the correct one?

**Comment by nicco91** [comment]
Hi @Khaledgarbaya,
yes, the environment develop exists, the accessToken is correct and the api keys are enabled for both spaces.

![image](https://user-images.githubusercontent.com/17545588/42889217-2d614012-8aaa-11e8-992e-91d4ea55c127.png)

**Comment by Khaledgarbaya** [comment]
Hey @nicco91,
You are using the content delivery key, the migration tool needs the content management key.

**Comment by nicco91** [comment]
Hi @Khaledgarbaya, I have always used that key before, when I ran migrations with the cli, and that worked properly. What the content management key is?

**Comment by Khaledgarbaya** [comment]
Hi @nicco91,
The contentful-cli does not use that key it authenticate you and save the management token in your rc file.
Here is a [video](https://www.contentful.com/developers/bits-and-bytes/#how-to-create-and-use-a-personal-access-token) on how you can create the correct token

**Comment by nicco91** [comment]
Hi @Khaledgarbaya 
I used the management token and it seems to work.
But something it's not clear to me.
I already has logged in with the contentful client and created the CMA token. Althought, for the single space configuration, I used to pass the CDA token, and I did that until now.
I don't understand why now is required the CMA token. Is that a new implementation?
Thank you for the help, anyway.

**Comment by Khaledgarbaya** [comment]
Hi @nicco91,
There is nothing new implemented, it is impossible to use the delivery token which is read-only with the migration tool in all of the versions because it requires to do write operation thus it need always the management token.
I think there might a confusion in your side 

Best,
Khaled

**Comment by OskarKaminski** [comment]
Please fix your docs because you everywhere refer "Personal Management Key" as "Access Key". There are 3 access keys in CF - Delivery, preview and personal management...
