### ISSUE TITLE
Pass callback instead of filePath

### ISSUE THREAD

**Issue by Slyke** [contentful/contentful-migration#1216]
## Expected Behavior

Want to be able to pass a callback function into the `options` field for the `runMigration()` function, instead of just `filePath`.

Reopening https://github.com/contentful/contentful-migration/issues/507 since it was closed without checking if it was still needed.

## Actual Behavior

There currently doesn't appear to be an option to do this.

## Possible Solution
Add in a callback property into the options object that's passed into the `runMigration()` function, that passes in the `migration` and `context` properties. Perhaps just call it `callback`? Raise an error if both, or neither of `filePath` and `callback` are specified. Only one can be specified.

## Context

Trying to create scriptable migrations that don't rely on files being passed into code.

## Environment

All

**Comment by marcolink** [comment]
Hi @Slyke,
would you be able to provide a bit more information about the use-case for the callback?

**Comment by Slyke** [comment]
Hey, @marcolink , there's some more information in this comment: https://github.com/contentful/contentful-migration/issues/507#issuecomment-724333235 but essentially it allows the "contents" to be passed as the return of a function instead of needing an actual file to be written to disk.


From this example:

https://github.com/contentful/contentful-migration#usage-as-a-library

```
const { runMigration } = require('contentful-migration')
const options = {
  callback: () => { // # Add this
    up: (migration) => { /* up code here */ },
    down: (migration) => { /* down code here */ },
    description: '<migration-description>'
  },
  spaceId: '<space-id>',
  accessToken: '<access-token>'
}
runMigration(options)
  .then(() => console.log('Migration Done!'))
  .catch((e) => console.error(e))
```

**Comment by Slyke** [comment]
Right now I'm writing temporary files to disk, then deleting them; which is not good when this data can be passed directly into the function without needing to worry about all the file handling code and edge cases.

**Comment by marcolink** [comment]
I"m not sure if I fully understand it - by `contents` you mean the string content of a migration file?

And about the callback object, this looks like an opinionated up and down call within a single migration 🤔

**Comment by Slyke** [comment]
Not the string value, but the object.

Here's a more full example:

Given a file with the migration:
```
module.exports.description = 'Some test migration'

module.exports.up = (migration) => {
  const contentModelMigration = migration.createContentType('testContentModelMigration')
    .name('The Content Model')
    .displayField('name')
    .description('')

    contentModelMigration.createField('name')
    .name('Name')
    .type('Symbol')
    .localized(true)
    .required(true)

    contentModelMigration.changeFieldControl('name', 'builtin', 'singleLine')
}

module.exports.down = migration => migration.deleteContentType('testContentModelMigration')
```

The code should be something like:
```
const theMigration = async () => ({ // async for handling promises or await use cases
  description: 'Some test migration',
  up: (migration) => {
    const contentModelMigration = migration.createContentType('testContentModelMigration')
      .name('The Content Model')
      .displayField('name')
      .description('')
  
      contentModelMigration.createField('name')
      .name('Name')
      .type('Symbol')
      .localized(true)
      .required(true)
  
      contentModelMigration.changeFieldControl('name', 'builtin', 'singleLine')
  },
  down: migration => migration.deleteContentType('testContentModelMigration')
});

const { runMigration } = require('contentful-migration')
const options = {
  callback: theMigration,
  spaceId: '<space-id>',
  accessToken: '<access-token>'
}
runMigration(options)
  .then(() => console.log('Migration Done!'))
  .catch((e) => console.error(e))
```

**Comment by marcolink** [comment]
If I understand you correctly, you want to use it as a library. this is also possible See [here](https://github.com/contentful/contentful-migration#usage-as-a-library). For your up/down logic, you would need to build your own custom code around it.

**Comment by Slyke** [comment]
Hey @marcolink yes, that's the link I gave above and where I got the code example from. The issue is that the options object only accepts a file path when it should instead be accepting an object with up/down in it such as in the example code I provided. 

If there's some code that can be wrapped around it, that doesn't involve writing files to disk, or some other way to use `runMigration` without writing files to disk please let me know!

**Comment by marcolink** [comment]
[Here](https://github.com/contentful/contentful-migration/blob/master/examples/specify-migration-function.js#L21) is an example where a migration function is directly passed to `runMigration` . 
It"s also defined in the [types](https://github.com/contentful/contentful-migration/blob/master/index.d.ts#L12). 

Please let me know in case I'm missing something. 

And about your up/down request, that"s something you would need to build on top of this library. |
There are some existing open source projects wrapping contentful-migration to allow up and down migrations.

**Comment by Slyke** [comment]
Oh perfect! That works too. Can just pass in our own up/down from a process param. Thank you!
