### ISSUE TITLE
Image mime type/subtype validation restrict to specifc files

### ISSUE THREAD

**Issue by samjeffress** [contentful/contentful-migration#1217]
## Expected Behavior

Adding a migration to restrict the type of image formats (e.g. jpeg / png only) should prevent you from publishing invalid formats and allow publishing the correct formats

## Actual Behavior

I am unsure how to achieve the behavior - please let me know if this is possible :) 

## Context
The content type / field already exists
```
module.exports.up = (migration) => {
  const seoMetadata = migration
    .createContentType("seo-metadata")
    .name("SEO Metadata")
    .description("This is the SEO metadata")
    .displayField("title")

  seoMetadata
    .createField("title")
    .name("Title")
    .type("Symbol")
    .required(true)
    
  seoMetadata
    .createField("image")
    .name("Meta Image")
    .type("Link")
    .linkType("Asset")
    .required(true)
    .validations([
      {
        linkMimetypeGroup: ["image"],
        message: "Please attach an image."
      }
    ])
}
```
Adding validations to the restrict the image type:
```
module.exports.up = (migration) => { 
 const contentType = migration.editContentType("seo-metadata")
  contentType.editField("image").validations([
    {
      linkMimetypeGroup: ["image/jpeg", "image/png", "image/avif"],
      message: "Please attach an image (JPEG, PNG or AVIF format)."
    }
  ])
}
```

After running this migration (which gets applied) I'm not able to publish new images including png and jpeg files - `Error publishing “This is a test page :)”: Validation failed. Please check the individual fields for errors.`

I created a new environment and replacing this validation with a direct call to the contentful-management package 
```
const contentfulManagement = require('contentful-management')
module.exports.up = async (migration, { spaceId, accessToken }) => { 
    const client = contentfulManagement.createClient({ accessToken })
    const space = await client.getSpace(spaceId)
    const contentType = await space.getContentType('seo-metadata')
    const mediaField = contentType.fields.find(field => field.id === 'image')
    mediaField.validations = [
      {
        linkMimetypeGroup: ['image/jpeg', 'image/png', 'image/avif'],
        message: "Please attach an image (JPEG, PNG or AVIF format).",
      }
    ]
    await contentType.update()
}
```
After this I was able to publish webp images which should be prevented. 

## Environment

-   **Node Version**: 16.19.1
-   **Package Manager Version**: 8.19.3
-   **Operating System**:  Mac m2
-   **Package Version**: 0.17.0

**Comment by marcolink** [comment]
Hi @samjeffress,

can you check if there is a difference in the resulting content type?
You can do this by checking the validations with the JSON preview in the UI 

<img width="883" alt="Screenshot 2023-06-14 at 09 06 58" src="https://github.com/contentful/contentful-migration/assets/156505/bae6683a-3d1f-4b1e-b1ad-99b42f4b31a2">

**Comment by samjeffress** [comment]
Hey @marcolink , thanks for the tip about viewing the content type in the UI. 

Looking at the JSON preview of the content type showed me that my use of the contentful management api was incorrect (there was a warning about `space.getContentType` but the migration still worked). 

Once I fixed that up the migration using the management api applied changes - now both migration scripts result in the  same content type:
```
{
  "id": "image",
  "name": "Meta Image",
  "type": "Link",
  "localized": false,
  "required": true,
  "validations": [
    {
      "linkMimetypeGroup": [
        "image/jpeg",
        "image/png",
        "image/avif"
      ],
      "message": "Please attach an image (JPEG, PNG or AVIF format)."
    }
  ],
  "disabled": false,
  "omitted": false,
  "linkType": "Asset"
}

```

However, the migration contentType.editField("image").validations does not allow any images where the migration using the management api allows all images (jpg, webp etc). 


The updated managment api script is:
```
module.exports.up = async (migration, { spaceId, accessToken }) => {
    const client = contentfulManagement.createClient({ accessToken  })
    const space = await client.getSpace(spaceId)
    const env = await space.getEnvironment('dig838')
    const contentType = await env.getContentType('seo-metadata')
    const mediaField = contentType.fields.find(field => field.id === 'image')
    mediaField.validations = [
      {
        linkMimetypeGroup: ['image/jpeg', 'image/png', 'image/avif'],
        message: "Please attach an image (JPEG, PNG or AVIF format).",
      }
    ]
    await contentType.update()
}
```
Any ideas?

**Comment by marcolink** [comment]
@samjeffress 
I"m not sure if I get this sentence: 

> However, the migration contentType.editField("image").validations does not allow any images where the migration using the management api allows all images (jpg, webp etc).

Are you saying that the migration script, and the changes done directly through `contentful-management.js` resolve in identical results, but behave differently?

If so, what is the difference in behaviour? :)

**Comment by samjeffress** [comment]
Unfortunately @marcolink, that is what it looks like. 

I've verified that before I run any change that I can select any image type and publish the image asset. I can use existing assets or attach new ones. 

When using the migration script:
* I am unable to publish the seo-metadata content type with any image format (valid png or invalid webp)
* I am unable to select existing assets (the list of assets is empty)
<img width="760" alt="image" src="https://github.com/contentful/contentful-migration/assets/1442081/58db5cd8-9697-4dcb-aac6-ac3eed28793e">
* The migration script output's the following:
``` 
Processing seo-metadata
  up : 20230614094122-restrict-image-formats.js
The following migration has been planned

Environment: dig838

Update Content Type seo-metadata

  Update field image
    - validations: [{"linkMimetypeGroup":["image/jpeg","image/png","image/avif"],"messag
e":"Please attach an image (JPEG, PNG or AVIF format)."}]

Publish Content Type seo-metadata
  ✔ Update Content Type seo-metadata
🎉  Migration successful
```


When using the `contentful-management.js`:
* I can publish the seo-metadata content type with any image format
* I can still select existing assets
* the script output's the following : 
```
Processing seo-metadata
  up : 20230614094122-restrict-image-formats.js
finished
The following migration has been planned

Environment: dig838


🎉  Migration successful
```

**Comment by marcolink** [comment]
@samjeffress this is a good question!
 
The docs only reference the basic media types. Which actually makes sense since you can define the fetched image type via [Image api](https://www.contentful.com/developers/docs/references/images-api/#/reference).

I also double checked with the team, and this is currently not possible.

**Comment by marcolink** [comment]
Closing this for now.

Let me know if you want me do forward this as a feature request to the product team.

**Comment by samjeffress** [comment]
Thanks for your help @marcolink 

I'd like to add this as a feature request please :)
