### ISSUE TITLE
Failed or aborted migration does not exit with non zero exit code

### ISSUE THREAD

**Issue by lucasvanlierop** [contentful/contentful-migration#126]
## Expected Behavior

Failing or aborted migration exits with a non zero exit code

## Actual Behavior

Failing or aborted migration exits with exit code 0

### To make sure failed migrations result in a non zero exit code

throw an error at:
https://github.com/contentful/contentful-migration/blob/af94ffe934e8a4cfcb7a2de06b95fe3a5d4daeef/src/bin/lib/render-migration.ts#L38

Catch this error and convert it to a non zero exit code at:
https://github.com/contentful/contentful-migration/blob/0b6738301550a5064936e1b0acc1d78934cf3166/src/bin/cli.ts#L121

### To make sure aborted migrations result in a non zero exit code

Throw a non zero exit code at:
https://github.com/contentful/contentful-migration/blob/0b6738301550a5064936e1b0acc1d78934cf3166/src/bin/cli.ts#L192

We could make a Pull request for this if you want?

## Steps to Reproduce

Run a migration conaining errors (a typo for exampl) OR abort a migration and display the exit code (`echo $?`)

## Context

Since Contentful CLI is not able to keep track of which migrations have already been executed we've created some scripts to do this. These scripts use the exit code to determine whether a migration has been successfully executed. For now we worked around the issue by checking for the strings `Error` and `aborted` in the CLI output.

## Environment
I left out other details since the bug is pretty obvious
Contentful CLI 0.14.2

**Comment by lucasvanlierop** [comment]
^ @M3kH

**Comment by Khaledgarbaya** [comment]
this fix in https://github.com/contentful/contentful-migration/pull/118

**Comment by Khaledgarbaya** [comment]
available in `v0.11.1`
