### ISSUE TITLE
Enable strikethough rich text type in validation schema 

### ISSUE THREAD

**Issue by JoeVinten** [contentful/contentful-migration#1321]
Now that strikethrough is available in the rich text items. Strikethrough should be enabled by adding it into the field-validations-schema.ts and also updating the corresponding example.

**Comment by jjolton-contentful** [comment]
Hey @JoeVinten looks like you acknowledged this got fixed up in https://github.com/contentful/contentful-migration/pull/1322, thanks very much for reporting, I'll go ahead and close this out now but please reopen if there is something I missed and there is still something to be done here.
