### ISSUE TITLE
Changing field ID does not work

### ISSUE THREAD

**Issue by jpowell** [contentful/contentful-migration#137]
## Expected Behavior

Changing field ID should work

## Actual Behavior

The migration is unsuccessful because the ID of the field in the `controls` does not match.

## Possible Solution

modify the ID reference in the `controls` config upon calling `changeFieldId` or `newId`

## Steps to Reproduce

use any of the above methods (`changeFieldId` or `newId`) in a migration

## Context

Modifying an existing field to rename the ID in order to preserve the data that currently exists. Modification in place instead of creating a new field and migrating, then deleting the old field.

## Environment

-   **Node Version**: v10.10.0
-   **Package Manager Version**: 6.4.1
-   **Operating System**: Darwin 16.7.0 Darwin Kernel Version 16.7.0: Fri Apr 27 17:59:46 PDT 2018; root:xnu-3789.73.13~1/RELEASE_X86_64 x86_64
-   **Package Version**: 0.12.1

**Comment by jpowell** [comment]
Yes, there was an editor interface attached to the fields. Isn't there always at least the default for the field type?

I've implemented a workaround in the migration to add a new field for the `id` & `name` we desire, and using `transformEntries` to populate it, then deleting the old field.

This is still an issue if it doesn't work as advertised / errors on using it.

The migration looked something like:
```typescript

const ct = migration.editContentType('someType')

ct.changeFieldId('oldId', 'newId')

// Other attempt
ct.editField('otherField')
  .newId('newFieldId')
  .name('Other Name')
```

**Comment by Khaledgarbaya** [comment]
This should be fixed in the latest release
