### ISSUE TITLE
Provide option to decrease verbosity when running migrations

### ISSUE THREAD

**Issue by geoffhardy1** [contentful/contentful-migration#153]
## Expected Behavior

Provide option to decrease verbosity when running migrations. Ideally it would be nice to only see any errors that are reported.

## Actual Behavior

Currently migrations create a large amount of logging output. 

## Possible Solution

Perhaps add an option for useVerboseLogging.

## Context

We are running a large number of migration scripts (>100) at a time and we are not interested in seeing all the low level details.

## Environment

-   **Operating System**: Windows 10
-   **Package Version**: 0.9.0

**Comment by makinwab** [comment]
Closing this issue as it has been attended to by #172 .
