### ISSUE TITLE
Misspelling in examples

### ISSUE THREAD

**Issue by zetlan** [contentful/contentful-migration#155]
https://github.com/contentful/contentful-migration/blob/65c7c790c74fe7648660333aa979cbf4b49458cd/examples/04-steps-errors.js#L6

"nmae" should be "name"
"lodalised" -> "localised"

**Comment by Khaledgarbaya** [comment]
Hey @zetlan,
That's on purpose to showcase how the tool can detect invalid properties.

Cheers,
Khaled
