### ISSUE TITLE
extend support of update functionality for targetCT using transformEntriesToType

### ISSUE THREAD

**Issue by keyurpatel** [contentful/contentful-migration#168]
`transformEntriesToType` is a cool addition, but unfortunately it only creates a new entry in targetContentType.

It will be super awesome if `transformEntriesToType` can extend its functionality to do either `create/update` operation on targetContentType.

**P.S**
I am happy to extend `update` support by contributing to the repository.

## Possible Solution

Here is  the line of code which shows, the only use of `createEntry` using `transformEntriesToType`
https://github.com/contentful/contentful-migration/blob/master/src/lib/action/entry-transform-to-type.ts#L79

This can be further extended to support `update` in `targetCT` using optional `updateTargetField` flag.

## Context

**Sceanrio**
```
sourceCT field name
targetCT field name

- copy value of field name from sourceCT to targetCT (more like update operation)
```

**Comment by Khaledgarbaya** [comment]
Hey @keyurpatel,
That sounds like a good addition and contributions are always welcome

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.
