### ISSUE TITLE
Contentful migration is not working

### ISSUE THREAD

**Issue by nikhilkumar14** [contentful/contentful-migration#171]
## Expected Behavior

Run a contentful migration

## Actual Behavior
Not able to run contentful migrations (most basic one*), getting this error:

PS C:\Users\nk10725\CMS> contentful space migration --space-id xxxxxxxxxxxxx  example1.js

[warning] Connection error occurred. Waiting for 2018 ms before retrying...
[warning] Connection error occurred. Waiting for 2678 ms before retrying...
[warning] Connection error occurred. Waiting for 3355 ms before retrying...
[warning] Connection error occurred. Waiting for 4544 ms before retrying...
[warning] Connection error occurred. Waiting for 6255 ms before retrying...
The provided space does not exist or you do not have access.

🚨  Migration unsuccessful
PS C:\Users\nk10725\CMS>

 migration example:

module.exports = function (migration, context) {
  const demo = migration.createContentType('demo');
  demo
    .name('demo')
    .description('Demo for Migration')
};

## Possible Solution

When I am trying the migration script outside corporate network its working fine. But inside corporate network its giving the above error.

## Environment

-   **Node Version**: v8.11.3
-   **Package Manager Version**: 6.7.0
-   **Package Version**: 0.20.0

**Comment by nikhilkumar14** [comment]
can someone from contentful team help me here

**Comment by phoebeschmidt** [comment]
Hi @nikhilkumar14 do you perhaps need to configure the contentful cli to run with a proxy?

You can add proxy host and port using `contentful config add --proxy <proxy here>` where you supply a proxy configuration in HTTP auth format: "host:port" or "user:password@host:port"

hope this helps!
