### ISSUE TITLE
running migration resets custom sidebar 

### ISSUE THREAD

**Issue by formatlos** [contentful/contentful-migration#173]
I'm using a custom sidebar for a content-type, but after running any migration on that content-type (e.g. adding a field) the sidebar gets reset to the default one. 

This is quite odd, as my migrations run automated and because of this issue theres an additional manual step to re-configure the sidebar. 

Is there any way to avoid this?

**Comment by suevalov** [comment]
@formatlos 
It's a known issue and we're planning to fix the issue this week. Sorry for inconvenience and thanks for bringing this up!
