### ISSUE TITLE
Successful migration using dropdown widget results in error in Contentful content model

### ISSUE THREAD

**Issue by yanneves** [contentful/contentful-migration#176]
Ran into an issue scripting a migration today, where I could successfully define a dropdown widget (or omit since this is default appearance anyway) for a `Symbol` field type using `validations: [{ in: [] }]`.

## Expected Behavior
Either through defining explicitly `<contentType>.changeEditorInterface(<fieldId>, 'dropdown')` or without, the content model in Contentful should use the dropdown appearance for this field.

## Actual Behavior
Migration is successful, but when attempting to create an entry using the content type, the following error appears in Contentful UI:

> The selected widget cannot be used with this field.
> Please select a valid widget in the Content Model section.

![image](https://user-images.githubusercontent.com/1331877/55432862-4bfe7980-5594-11e9-8e1d-7092dabb1981.png)

## Possible Solution
At the moment, workaround is to edit the content model directly in Contentful UI using the field that was added / changed using the migration script and select the dropdown appearance again. Save the content model and the field now works properly.

## Environment
-   **Node Version**: v11.12.0
-   **Package Manager Version**: v6.7.0
-   **Operating System**: Linux
-   **Package Version**: contentful-migration@0.17.1

**Comment by julka** [comment]
I'm having this problem with `<contentType>.changeEditorInterface(<fieldId>, 'datePicker')` and a custom widget as well.

**Comment by Khaledgarbaya** [comment]
Hi @yanneves,
Can you provide the migration script and the JSON payload of the content type, you can get that from the JSON tab on the Content-type page.

**Comment by yanneves** [comment]
Thanks @Khaledgarbaya, I can no longer reproduce the issue so assume it's fixed in the Contentful API. May also be worth retrying in your case @julka.

**Comment by Amerr** [comment]
@Khaledgarbaya 
this is my migration script 
```
var seoHeroComponent = migration.editContentType('seoHeroComponent');
seoHeroComponent.changeFieldControl('title', 'builtin', 'multipleLine');
seoHeroComponent.changeFieldControl('title', 'builtin', 'multipleLine');
```

i also face this issue when i try to run two  ` changeFieldControl ` simulataneously 

```
Error: Cannot save CT seoHeroComponent because it does not exist
    at OfflineAPI.saveContentType (/Users/amerrnathmurugan/.nvm/versions/node/v10.13.0/lib/node_modules/contentful-cli/node_modules/contentful-migration/built/lib/offline-api/index.js:166:19)
    at ContentTypeSaveAction.applyTo (/Users/amerrnathmurugan/.nvm/versions/node/v10.13.0/lib/node_modules/contentful-cli/node_modules/contentful-migration/built/lib/action/content-type-save.js:10:19)
    at IntentList.applyTo (/Users/amerrnathmurugan/.nvm/versions/node/v10.13.0/lib/node_modules/contentful-cli/node_modules/contentful-migration/built/lib/intent-list/index.js:108:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by Khaledgarbaya** [comment]
Hi @Amerr,
Please make sure that you Content Type (CT) exist

**Comment by Amerr** [comment]
@Khaledgarbaya  the Content Type exist and this error is thrown when i try to execute the above statements simultaneously , when i run it individually there is no error. But at the same time, the control field is selected for the particular field.

when I try to get the editor_interfaces for the particular field, the response is 
```
{
sys: {
type: "Error",
id: "NotFound"
},
message: "The resource could not be found.",
details: {
type: "ContentType",
id: "seoHeroComponent",
environment: "master",
space: "zqe91pmti9ii"
},
requestId: "41704b8f0c65cf16fd5f8b5382e8b1a5"
}```

**Comment by Khaledgarbaya** [comment]
@Amerr,
I would be nice if you can opena separate issue and describe it there

**Comment by paul-grant-hs** [comment]
In case anyone finds this issue for the same reason I did, I hope my mistake will help. I had the following code:

```ts
const card = migration
  .createContentType('card')
  .name('Card')
  
card
  .createField('topic')
  .name('Topic')
  .type('Link')
  .linkType('Entry')
  .validations([
    ...
  ])
  
card
  .changeFieldControl('topic', 'builtin', 'entryLinksEditor', { helpText: '...' })
```
Originally, I had my `topic` field as an Array of entry links, and later changed it to a single entry link. I neglected to change `entryLinksEditor` to `entryLinkEditor` when I changed my field control.
