### ISSUE TITLE
Simple migration script working partially

### ISSUE THREAD

**Issue by constantin-v** [contentful/contentful-migration#177]
## Expected Behavior

Migration script to work properly and give feedback

## Actual Behavior

Migration script not responding, even after 5 minutes.

## Possible Solution

No idea why it's not working as it's a normal usage

## Steps to Reproduce

1. Copy the code from [contentful cli example](https://github.com/contentful/contentful-migration/blob/master/examples/16-change-editor-interface.js) and save it to migration.js
2. Execute the script with `contentful space migration  --space-id xxxx --environment-id xxxx(not master) --access-token xxxx migration.js`

The result is : 

- The blog post content is created with the slug field but the editor interface of slug is the default one (meanings that this migration is not done)
- The script is stuck at "Do you want to apply the migration ? Yes" 

## Environment

-   **Node Version**: 10.8.0
-   **Package Manager Version**: 6.2.0
-   **Operating System**: Windows 64bit
-   **Contentful Cli**: 0.26.2

**Comment by CodingCreate101** [comment]
Hi, I am facing the same issue. Did you figure out any solution to this?

**Comment by Khaledgarbaya** [comment]
Hi @constantin-v,
This could be related to a race condition. To workaround this you can split the migration into 2 files.

```js
// first file create content type first
const blogPost = migration.createContentType('blogPost', {
    name: 'Blog post',
    description: 'super angry'
  });
  blogPost.createField('slug', {
    name: 'URL Slug',
    type: 'Symbol',
    required: true
  });
```

```js
// second file
  const blogPost = migration.editContentType('blogPost');
  blogPost.changeEditorInterface('slug', 'slugEditor');
```
