### ISSUE TITLE
Enhance Derived Entries to link to Source

### ISSUE THREAD

**Issue by mlkirkpatrick** [contentful/contentful-migration#184]
`deriveLinkedEntries` (and its close cousin, `transformEntriesToType`) provides an option to update the source item with a reference to the newly derived entry. I need the reference to go the other direction: target -> source.

Seems like this should be simple, but there doesn't seem to be a way to reference the source entry id during a migration.

**Comment by marcolink** [comment]
Hi @mlkirkpatrick 👋 
We have just added the entry id to all transform callbacks
https://github.com/contentful/contentful-migration/pull/1212
