### ISSUE TITLE
Migration gets stuck(?)

### ISSUE THREAD

**Issue by freder** [contentful/contentful-migration#185]
I need to convert an existing link field to one that allows multiple references. running this creates the new field, but seems to get stuck on populating the new field:

```js
module.exports = (migration) => {
  const product = migration.editContentType('product');
  product
    .createField('categories')
    .name('Categories')
    .type('Array')
    .items({
      type: 'Link',
      linkType: 'Entry',
      validations: [
        { linkContentType: ['category'] },
      ],
    });

  migration.transformEntries({
    contentType: 'product',
    from: ['category'],
    to: ['categories'],
    transformEntryForLocale: (fromFields, locale) => {
      if (!fromFields.category) {
        return;
      }
      const cat = fromFields.category[locale];
      return { categories: [cat] };
    },
  });
};
```

## Expected Behavior
should pre-polutate the array with the value of the existing `category` field.

## Actual Behavior
gets stuck doing this over and over again:
<img width="670" alt="Screenshot 2019-05-14 at 13 26 14" src="https://user-images.githubusercontent.com/724844/57695127-bc95bd00-764d-11e9-8aa9-98828fa4ea91.png">

it's always request `1/1914`...

## Environment

-   **Package Version**: 0.17.3

**Comment by Khaledgarbaya** [comment]
Hi @freder,

could also check for the value of `fromFields.category[locale]`

```js
if (!fromFields.category || fromFields.category[locale]) {
        return;
}
```

**Comment by freder** [comment]
hmm, for some reason I didn't think `category[locale]` could be `undefined`. — that solves my problem.

thank you, @Khaledgarbaya!
