### ISSUE TITLE
Update examples or documentation to include migration of unsupported markdown

### ISSUE THREAD

**Issue by georgialoper** [contentful/contentful-migration#191]
## Expected Behavior

Step 11 of the [Migrate content to rich text](https://www.contentful.com/developers/docs/tutorials/general/migrate-to-rich-text/) tutorial suggests migrating markdown with unsupported functionalities to linked entries and then tying them to the rich text, but does not provide an example.

## Context

I am trying to migrate markdown that contains code blocks to a rich text field.
The tutorial suggests migrating the content into a linked entry which only has a Markdown field with the supported content by doing something similar to the Convert the Markdown text in “Lesson > Copy” to Rich Text step, so I've been hacking that around. Below is my code atm, but I am getting "RateLimitExceeded" errors

```
const { richTextFromMarkdown } = require('@contentful/rich-text-from-markdown');
const _ = require('lodash');
const { createClient } = require('contentful-management');

module.exports = function(migration, { makeRequest, spaceId, accessToken }) {
const articles = migration.editContentType('articles');
  articles.createField('articleBuilder').name('Article Builder').type('RichText').required(true);
  migration.transformEntries({
    contentType: 'articles',
    from: ['body'],
    to: ['articleBuilder'],
    transformEntryForLocale: async function(fromFields, currentLocale) {
      const allNodeArrays = await transformBody(fromFields, currentLocale);

      async function transformBody(fromFields, locale) {
        const copy = fromFields.body[locale];
        return await richTextFromMarkdown(copy, async mdNode => {
          // Create and asset and publish it
          const space = await managementClient.getSpace(spaceId);
          // Unfortunately, we can't pull the environment id from the context
          const environment = await space.getEnvironment('test');

          let asset = await environment.createEntry('blockText', {
            fields: {
              text: {
                'en-US': copy
              }
            }
          }).then((entry) => console.log(entry))
          .catch(console.error);
          asset = await asset.processForAllLocales({
            processingCheckWait: 4000
          });
          asset = await asset.publish();
          console.log(`published asset's id is ${asset.sys.id}`);
          return {
            nodeType: 'embedded-asset-block',
            content: [],
            data: {
              target: {
                sys: {
                  type: 'Link',
                  linkType: 'blockText',
                  id: asset.sys.id
                }
              }
            }
          };
        });
      }
      // The content property of the Rich Text document is an array of paragraphs, embedded entries, embedded assets.
      const content = _.flatten(allNodeArrays);

      // The returned Rich Text object to be added to the new "copy" field
      var result = {
        copy: {
          nodeType: 'document',
          articleBuilder: content,
          data: {}
        }
      };
      return result;
    }
  })
}
```

**Comment by TimBeyer** [comment]
Hey @georgialoper, did you figure this out already by now?

```js
const space = await managementClient.getSpace(spaceId);
// Unfortunately, we can't pull the environment id from the context
const environment = await space.getEnvironment('test');
```
There should actually be an `environmentId` property on the context

```js
let asset = await environment.createEntry('blockText', {
  fields: {
    text: {
      'en-US': copy
    }
  }
}).then((entry) => console.log(entry))
  .catch(console.error);
asset = await asset.processForAllLocales({
  processingCheckWait: 4000
});
asset = await asset.publish();
```

You also probably already noticed by now that you created an entry there and then proceeded to treat it like an asset.

Not sure though why you'd be getting `RateLimitExceeded` errors.
In theory those should all be retried, but maybe the SDK is being a bit noisy about it.

Overall your approach looks like it should work and is currently probably the best way for this kind of flow.

I'm not sure we should add this as an additional example in the docs though since it's really quite similar to the approach in https://www.contentful.com/developers/docs/tutorials/general/migrate-to-rich-text/#8-convert-the-markdown-text-in-lesson-copy-to-rich-text and really depends on what particular approach the user chooses.

I'll close this for now, feel free to reopen in case there are still questions.
