### ISSUE TITLE
changeFieldControl does not seem to work correctly with custom extensions

### ISSUE THREAD

**Issue by ThomasJacobsAppno** [contentful/contentful-migration#198]
Hi,

I tried using changeFieldControl within a migration script to change the control to a custom extension (and apply settings). In the below example I tried using the "Bynder Assets" plugin from the marketplace, but I have also attempted this with my own custom plugin.

`element.changeFieldControl('image', 'bynder-assets', 'extension', { bynderURL: 'URL_VALUE'});`

When I check the content element afterwards, the control isn't set to any widget (not even the default one). The field was created like this:

`element.createField('image').name('Image').type('Object').localized(true).required(false).disabled(false).omitted(false)`

The strange part is, that the "bynderURL" property was set correctly on the widget, so this seems to be an issue with the migration itself.

Thanks in advance.

**Comment by Khaledgarbaya** [comment]
Hi @ThomasJacobsAppno,
could that be related to the [issue](https://github.com/contentful/contentful-migration/pull/199) we had in the documentation?

**Comment by ThomasJacobsAppno** [comment]
@Khaledgarbaya, I noticed that. It is possible. Although the method parameters are now the same as in the documentation (and my example above).

I just checked this further and I may have found the issue in https://github.com/contentful/contentful-migration/blob/master/src/lib/migration-steps/index.ts at line 148. The parameters are still in a different order there.

I am not sure which order should be correct, but they should definitely be the same (I would think).

**Comment by lehnerm** [comment]
@ThomasJacobsAppno you are correct, the argument order between docs and actual implementation is inconsistent. Your usage, assuming `bynder-assets` is the extension id, is correct for the current version though.

Is `bynder-assets` the actual id of the bynder extension installed in your space?  Please note that the marketplace installer does not give the extension a fixed named id, rather it will create a random one on installation. Can you please double check the id for your bynder installation?

Additionally, I just ran the following example after installing `bynder-assets` from the marketplace:
```
module.exports = function (migration) {
  const bynderExtensionId = '1X1j*********************'
  const contentType = migration.createContentType('bynder_demo', {
    name: 'Bynder Demo'
  });

  contentType.createField('asset', {
    name: 'Asset',
    type: 'Object',
    required: true
  });

  contentType.changeFieldControl('asset', bynderExtensionId, 'extension', {
    bynderURL: 'https://www.example.com'
  });
};
```
Content type and field are created as well as the correct plugin assigned to it.

**Comment by ThomasJacobsAppno** [comment]
@lehnerm : Thanks for the response. We hadn't realised that marketplace plugins created a randomised ID. That was indeed the issue.

This ticket can be closed then. I'll follow the PR status, so I know when to update.
