### ISSUE TITLE
changeFieldControl doesn't update date picker correctly

### ISSUE THREAD

**Issue by mkalpana** [contentful/contentful-migration#217]
## Expected Behavior

`changeFieldControl` should update the datePicker `ampm` setting correctly and display it in the editor as below.

<img width="650" alt="ExpectedWidgetAfterUpdate" src="https://user-images.githubusercontent.com/8776433/62668714-32e95780-b9d0-11e9-9578-a1523a57d211.png">

## Actual Behavior

The widget disappears in the Content view. It shows up as below:

<img width="848" alt="WidgetDoesn'tExistAnymore" src="https://user-images.githubusercontent.com/8776433/62668724-41d00a00-b9d0-11e9-9f4d-9040a10f3e29.png">

Inspecting the Content Model reveals that "Date Picker" field is no longer selected for the field.

<img width="830" alt="ContentModelForWidget" src="https://user-images.githubusercontent.com/8776433/62668753-61673280-b9d0-11e9-9e7e-999517010fb3.png">

## Possible Solution

Deprecated `changeEditorInterface` updates the `datePicker` field corrrectly.

## Steps to Reproduce

```
import { MigrationFunction } from 'contentful-migration';

export = function(migration) {
  // News Content Type with fields publishAt
  const news = migration.editContentType('news');
  news.changeFieldControl('publishAt', 'builtin', 'datePicker', {
    format: 'time'
  });
} as MigrationFunction;
```

## Environment

-   **Node Version**: 10.15.0
-   **Package Manager Version**: 6.4.1
-   **Operating System**: macOS Mojave - 10.14.6
-   **Package Version**: 0.19.0

**Comment by Khaledgarbaya** [comment]
this should be fixed in `v1.0.2`
