### ISSUE TITLE
Support `shouldPublish: 'preserve'` option in transformEntries

### ISSUE THREAD

**Issue by LeoBastian** [contentful/contentful-migration#223]
Transform functions supply the field `shouldPublish` to set whether or not a transformed entry should be published. `transformEntries` supports `boolean` only, while transform entry type supports `bool | 'preserve'`.

**I would like** `transformEntries` to support 'preserve' as well.

**Use case** I am creating a field `A` and want to set its value to the value of field `B`. If I use `shouldPublish: true` my migration will fail for drafts that don't set required fields. If I use `shouldPublish: false` then my migration works, but I have changed every effected entry to `changed` status and would have to publish each one again. 
Thus I would like them to keep their publishing state, if it was drafted stay drafted and vise versa.

**Comment by loremipson** [comment]
This is currently a big hang up for us. Can't migrate because we have a dozen (or so) entries that are in "Changed" state, with missing required fields.

**Comment by marcolink** [comment]
@LeoBastian, @loremipson 
This has been fixed with [release 2.0.0](https://github.com/contentful/contentful-migration/releases/tag/v2.0.0)
