### ISSUE TITLE
migration to markdown

### ISSUE THREAD

**Issue by kamilxunai** [contentful/contentful-migration#224]
hi, i try to migrate field from `Symbol - short text` to `Text - markdown` but have a little problem

## Expected Behavior

new field is `markdown`

## Actual Behavior
some field is markdown some isn't,
have issue if field is mark as content model title - in that situation default interface to field is `single line`

i try change it with ```editedModel.changeFieldControl(`${name}_MD`, "builtin", "markdown")```
this ends with success

but instead of markdown i got: 
![Screenshot 2019-09-26 12 57 22](https://user-images.githubusercontent.com/7757534/65683322-42466200-e05d-11e9-8456-c5e09d747411.png)

but when i check `appearance` in content model every seems to by ok
<img width="1198" alt="Screenshot 2019-09-26 10 47 19" src="https://user-images.githubusercontent.com/7757534/65683637-08299000-e05e-11e9-91fb-e523730395ba.png">

to by work, i must manually select this again as markdown and save this and content model

## Steps to Reproduce

1. have fields as `Symbol - single line`
<img width="908" alt="Screenshot 2019-09-26 09 54 42" src="https://user-images.githubusercontent.com/7757534/65684412-da454b00-e05f-11e9-90e9-66dc3290317b.png">
2. try to create new ones as `Text` and some mark its to be `displayField`
<img width="856" alt="Screenshot 2019-09-26 09 55 05" src="https://user-images.githubusercontent.com/7757534/65684774-c1896500-e060-11e9-8eff-1f7244d85d0d.png">

3. field marked to be `displayField` showed as `Text - single line`
4. run ```editedModel.changeFieldControl(`${name}_MD`, "builtin", "markdown")```
5. get error

## Environment

-   **Node Version**:  `v11.13.0`
-   **Package Manager Version**:  `6.7.0`
-   **Operating System**:  `Darwin Kernel Version 18.7.0`
-   **Package Version**:  ```contentful -v
0.36.2```

**Comment by jroehl** [comment]
Hi @kamilxunai,
thanks for your very detailed issue report 💯.

The problem is that you're trying to change the field **control** (`changeFieldControl`) of a short text to markdown - which is invalid. To change the field **type** (in your case from `Symbol ` to `Text`) you need to create a new field and transform the data:

```javascript
module.exports = migration => {
  const contentType = 'keyValue';
  const originalFieldId = 'key';
  const tempFieldId = `temp_${originalFieldId}`;
  const keyValue = migration.editContentType(contentType);

  keyValue
    .createField(tempFieldId) // create a new field with a temporary id
    .name('Key')
    .type('Text'); // and the new field type

  // set the new field control of the content type
  keyValue.changeFieldControl(tempFieldId, 'builtin', 'markdown');

  // if the field that will be changed is the display field of the content type
  keyValue.displayField(tempFieldId);

  // transform all entries
  migration.transformEntries({
    contentType,
    from: [originalFieldId],
    to: [tempFieldId],
    transformEntryForLocale: (fromFields, currentLocale) => {
      const value = fromFields[originalFieldId][currentLocale];
      if (!value) return;
      return { [tempFieldId]: value };
    },
  });

  // remove the old field
  keyValue.deleteField(originalFieldId);

  // change the temporary id back to the original
  keyValue.changeFieldId(tempFieldId, originalFieldId);
};
```

I hope this helps.

**Comment by kamilxunai** [comment]
we do some like this but in separate files

`migration-data.js`
```
const migrationData = [
  {
    type: "ctaButton",
    fields: [{ name: "title", actsAsTitle: true }],
  },
  {
    type: "post",
    fields: [
      { name: "title", actsAsTitle: true },
      { name: "ctaText", actsAsTitle: false },
      { name: "description", actsAsTitle: false },
    ],
  },
....
]

module.exports = {
  migrationData,
}
```

`09-create-md-fields-and-derive-content.js`
```
const { migrationData } = require("./migration-data")

module.exports = function(migration) {
  function addMdString(arrayOfFields) {
    return arrayOfFields.map(field => `${field}_MD`)
  }
  function transformToArray(arrayOfObjects) {
    return arrayOfObjects.map(item => item["name"])
  }

  migrationData.forEach(({ type, fields }) => {
    const editedModel = migration.editContentType(type)
    fields.forEach(({ name, actsAsTitle }) => {
      editedModel
        .createField(`${name}_MD`)
        .name(`${name}_MD`)
        .type("Text")

      editedModel.changeFieldControl(`${name}_MD`, "builtin", "markdown")

      if (actsAsTitle) {
        editedModel.displayField(`${name}_MD`)
      }
    })

    migration.transformEntries({
      contentType: type,
      from: transformToArray(fields),
      to: addMdString(transformToArray(fields)),
      transformEntryForLocale: async (from, locale) => {
        return fields.reduce((acc, field, index) => {
          const oldField = from[`${fields[index].name}`]
          return {
            ...acc,
            ...(oldField ? { [`${field.name}_MD`]: oldField[locale] } : {}),
          }
        }, {})
      },
    })
  })
}
```

`10-delete-old-fields.js`
```
const { migrationData } = require("./migration-data")

module.exports = function(migration) {
  migrationData.forEach(({ type, fields }) => {
    const editedModel = migration.editContentType(type)
    fields.forEach(({ name }) => {
      editedModel.deleteField(name)
    })
  })
}
```

`11-rename-md-fields.js`
```
const { migrationData } = require("./migration-data")

module.exports = function(migration) {
  migrationData.forEach(({ type, fields }) => {
    const editedModel = migration.editContentType(type)
    fields.forEach(({ name, actsAsTitle }) => {
      editedModel.editField(`${name}_MD`).name(name)
      editedModel.changeFieldId(`${name}_MD`, name)
      if (actsAsTitle) {
        editedModel.displayField(name)
      }
    })
  })
}
```

**Comment by jroehl** [comment]
So, does that mean it works for you now? :)
