### ISSUE TITLE
Yarn Audit reports dependency issue

### ISSUE THREAD

**Issue by galvogalvo** [contentful/contentful-migration#227]
When we run`yarn audit` we are seeing an issue with `https-proxy-agent` which needs to be upgraded to `3.0.0` or greater. This is causing our CI pipelines to fail.
https://www.npmjs.com/advisories/1184

**Comment by jroehl** [comment]
Resolved with #228

**Comment by jroehl** [comment]
The `dev-dependencies` (`semantic-release` and `codecov`) might still show the audit warning, relying themselves on an earlier version of `https-proxy-agent`. As they are only `dev-dependencies` this is no risk for production builds.

As soon as the dependency owners updated their packages, we will update our package again.
