### ISSUE TITLE
README needs update for changeFieldControl signature.

### ISSUE THREAD

**Issue by Nschulz88** [contentful/contentful-migration#233]
## Expected Behavior

The arguments that `changeFieldControl` takes should be:
`(fieldId, widgetId, widgetNamespace[, settings])`.

## Actual Behavior

They are currently shown as `(fieldId, widgetNamespace, widgetId[, settings])`.

**Comment by TimBeyer** [comment]
This was initially changed in https://github.com/contentful/contentful-migration/pull/195
 and subsequently fixed to use the consistent order with `namespace` coming first in https://github.com/contentful/contentful-migration/pull/203

Is it possible you were using an old version of this, or is there still an issue?

I'll close this for now, feel free to reopen if this still is an issue.
