### ISSUE TITLE
Contentful migration devDependencies fail

### ISSUE THREAD

**Issue by pratiksawant10** [contentful/contentful-migration#234]
Using the latest version of contentful-migration (1.0.6), when I run npm audit I run into a problem with the version of mem which is being used has a security vulnerability. This is breaking our builds, can anyone offer some advise please?

Steps to reproduce:

1) npm audit
2) Error Message:

`=== npm audit security report ===                        
                                                                                
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Denial of Service                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ mem                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.0.0                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ contentful-migration [dev]                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ contentful-migration > yargs > os-locale > mem               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1084                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 1 low severity vulnerability in 1766194 scanned packages
  1 vulnerability requires manual review. See the full report for details.`

**Comment by TimBeyer** [comment]
Fixed in https://github.com/contentful/contentful-migration/pull/322
