### ISSUE TITLE
TypeScript Typings are off on transformEntriesToType

### ISSUE THREAD

**Issue by bsgreenb** [contentful/contentful-migration#241]
pretty sure there’s a bug in the typescript typings for migration.transformEntriesToType https://github.com/contentful/contentful-migration/blob/master/index.d.ts#L267

The docs say that it should have sourceContentType and targetContentType fields https://github.com/contentful/contentful-migration#transformentriestotypeconfig

Think this prevents writing typescript migrations

![image](https://user-images.githubusercontent.com/980217/71534060-f9e34e00-28b0-11ea-8046-c331ec38b90b.png)

**Comment by ruderngespra** [comment]
Hey, thanks again @bsgreenb, I added the fix.
