### ISSUE TITLE
How do you migrate a specific content entry 

### ISSUE THREAD

**Issue by ScriptedAlchemy** [contentful/contentful-migration#244]
I'm wondering how one would migrate a specific content type from one environment to another.

After running a migration, if I were to make additional updates to `dev` environment - it throws errors ` Error: Entry with id '3757722282' already exists`

How can I migrate an entry by ID from a staging environment to master environment

Also, if I am migrating from stage to master - how do i specify the from - to 

```
const options = {
  filePath: require.resolve("./migrate-page"),
  spaceId: "oi43qwed",
  accessToken: "NotTellin",
  environmentId: "dev" // dies this mean sync from mastrer, to dev? or dev to master?
};
runMigration(options)
  .then(() => console.log("Migration Done!"))
  .catch(e => console.error(e));
```

**Comment by phoebeschmidt** [comment]
Hi @ScriptedAlchemy,

If you want to simply move content from one environment to another, I can recommend our import/export tooling (https://github.com/contentful/contentful-import and https://github.com/contentful/contentful-export). Or, if you simply want a copy of an existing environment, you can use the environment cloning feature (in the web app, create an environment and choose which source environment to clone from). 

Migrations are meant to transform your content model or content within one environment.

Hope this helps.
