### ISSUE TITLE
Incorrect main property in package.json

### ISSUE THREAD

**Issue by micksi** [contentful/contentful-migration#252]
## Expected Behavior
When importing a type from "contentful-migration" into a project it does so successfully.

## Actual Behavior
Unable to resolve path due to incorrect main specified in package.json

```
  ...
   "migrate"
  ],
  "license": "MIT",
  "main": "index", <--- this is right here
  "name": "contentful-migration",
  "nyc": {
    "per-file": true,
    "include": [
        ....
```

## Possible Solution
Change main property to point to a valid file.

## Context
The type is properly resolved but eslint shows red squiggly line warning about unresolved path "<my-project-dir>/node_modules/contentful-migration/index"

## Environment

-   **Node Version**: 12.14.1 
-   **Package Manager Version**: 6.13.7 
-   **Operating System**: MacOS 10.15.3 
-   **Package Version**: 1.0.12

**Comment by TimBeyer** [comment]
Was fixed in https://github.com/contentful/contentful-migration/pull/366
