### ISSUE TITLE
Adding existing extension via migration

### ISSUE THREAD

**Issue by bigtone1284** [contentful/contentful-migration#300]
Hello, my team and I use Contentful Migrations to manage our contentful space (in terms of creating new Content Types and editing these Content Types).

Via a Contentful Migration, is there a way to add an extension from Contentful's Extension [Samples](https://github.com/contentful/extensions/tree/master/samples)?

We don't use Contentful CLI directly in our project and would love to do something like this a migration. Thanks!

**Comment by TimBeyer** [comment]
You cannot manage extensions themselves with the migration tool, only with the extension tooling.  
What you can do is assign extensions to fields using [`changeFieldControl`](https://github.com/contentful/contentful-migration#changefieldcontrol-fieldid-widgetnamespace-widgetid-settings--void).

Probably the best thing for your use case would be to use Contentful CLI which has support for extension and migration commands.

Then you can something like

```
contenful extension create --id my-new-extension
contentful space migration ./migrations/use-new-extension.js
```

And have the migration assign the `fieldControl` where desired.
