### ISSUE TITLE
Unable to create new entries.

### ISSUE THREAD

**Issue by ozturkcangokkaya** [contentful/contentful-migration#302]
I've been trying to migrate my content from Ghost to Contentful, but got kinda confused about how to do it. What's the right way to migrate 250+ posts and their assets programmatically to contentful.

## Expected Behavior

To be able to create new entries with a simple function such as

```
createEntry({
  contentType: 'myContentType',
  title: 'New entry title',
  text: 'Some html data for richText field'
  ...
})
```

**Comment by TimBeyer** [comment]
Hi @ozturkcangokkaya, this project is mainly for iteratively applying changes to your content model and associated entries, like a DB migration.  
If you want to import a larger amount of data, it might be better to use https://github.com/contentful/contentful-import and map your content to the expected format.

That being said, we do understand that the ability to directly create entries might sometimes be really useful, and would enable use cases such as yours. We will definitely consider this for future improvements.
