### ISSUE TITLE
add version info and support reading from stdin

### ISSUE THREAD

**Issue by ddean** [contentful/contentful-migration#33]
It would be useful if the tool's current version was displayed in the help text and/or via a -v or --version command line param

also as a command line tool IMO it should be able to accept the migration script from stdin. I have a tool that generates migration scripts and would like to pipe the output of that directly into contentful-migration

Thanks!

**Comment by benben** [comment]
+1 for the version info!!

**Comment by Khaledgarbaya** [comment]
The version has been added
