### ISSUE TITLE
async transformEntryForLocale 

### ISSUE THREAD

**Issue by cajoy** [contentful/contentful-migration#362]
Hi, 

I have issue with migration scripts because I need to get values of referenced model. so briefly I have following structure

```
blogpost {
   ctaButton {
      title: string
      route: reference 
   }
}
```

now I need to convert it to:

```
blogpost {
   title: string
   route: reference 
}
```

But the problem is with `transformEntryForLocale`

1) It is not async so i can't get values with includes by using regular content api
or
2) It is not able to include referenced models so I can't extract values from one level below.

How can I transform one model to another?

**Comment by TimBeyer** [comment]
`transformEntryForLocale` can already be used in an `async` way, as can pretty much all the transform functions exactly for those kind of use cases.
Let me see if we can document that better.

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.
