### ISSUE TITLE
Identifier 'migration' has already been declared

### ISSUE THREAD

**Issue by DeathstarNovember** [contentful/contentful-migration#383]
## Actual Behavior

Running `contentful space migration -s xxxxxxx 01initialmigration.js` produces `SyntaxError: Identifier 'migration' has already been declared`

## Steps to Reproduce

1. use `contentful space generate migration ...`. to create migration file.
2. copy migration file into new project.
3. use `contentful space migration -s xxxxxxx <path to file>` to apply generated migration.

## Context

Initiating a new project with a migration.  

## Suspected problem

https://github.com/contentful/contentful-migration/blob/f3a37c6467e30455016dc0168d8b23db70b5ef39/src/lib/migration-steps/index.ts#L276

## Environment

-   **Language Version**: 10.15.3
-   **Package Manager Version**: 6.4.1
-   **Operating System**: Darwin Kernel Version 19.4.0
-   **Package Version**: 1.4.3

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.
