### ISSUE TITLE
Unknown argument: filename.js when running contentful space migration

### ISSUE THREAD

**Issue by yamnayemara** [contentful/contentful-migration#393]
Running **contentful space migration -s xxxxxxx filename.js** 
produces :
```
Parses and runs a migration script on a Contentful space.

Usage: contentful space migration [args] <path-to-script-file>

Script: path to a migration script.

Options:
  --version                 Show version number                        [boolean]
  --space-id, -s            ID of the space to run the migration script on
  --environment-id, -e      ID of the environment within the space to run the
                            migration script on
  --management-token, --mt  The Contentful management token to use
                            This takes precedence over environment variables or
                            .contentfulrc
  --yes, -y                 Skips any confirmation before applying the migration
                            script                                     [boolean]
  --quiet, -q               Reduce verbosity of information for the execution
                                                                [default: false]
  -h, --help                Show help                                  [boolean]
  --config                  An optional configuration JSON file containing all
                            the options for a single run

Examples:
  contentful space migration  --space-id abcedef my-migration.js

Copyright 2019 Contentful
Unknown argument: filename.js 
```

I tried to add all the args options but still the same error, the contenfulrc.json was founded as well. any ideas?

**Comment by yamnayemara** [comment]
updating: I tried to use a contentful-migration tool and run it through the node . it's worked as expected. so I think the problem with contentful_cli.

**Comment by 5VRod** [comment]
got exactly the same issue when using contentful space migration --space-id xxxxxxxxxxxx --environment-id 'dev' migrations/migrate-images.js

**Comment by 5VRod** [comment]
Got exactly the same issue, updating to the latest release (1.4.17 in my case) resolved the issue.

**Comment by pksimeonov** [comment]
Encountered on v1.4.20 too, downgraded to 1.4.17 and it worked.

**Comment by phoebeschmidt** [comment]
Thanks for bringing this to our attention, the team is working on a fix. In the meantime pin your deps to 1.4.17 sorry about that.

**Comment by phoebeschmidt** [comment]
sorry about that. This has been fixed in the CLI, newest version should work (1.4.24).

**Comment by georgemillard** [comment]
I'm seeing the same issue.

When I run `contentful space migration -s 'xxxxxx' --environment-id 'xxxxxx' migration.js`

I receive the error: `Unknown argument: migration.js`

I have tested on `1.4.17`, `1.4.24` and `1.4.6`
