### ISSUE TITLE
createEnvironmentFromId resolves too soon

### ISSUE THREAD

**Issue by loremipson** [contentful/contentful-migration#409]
## Expected Behavior

`await`ing environment creation with `createEnvironmentFromId()` should not resolve until the created environment is "complete".

## Actual Behavior

`createEnvironmentFromId()` resolves while the status is "queued" or "In Progress", and fails with a "The provided space does not exist, or you do not have access" error if a migration is attempted at this stage.

## Steps to Reproduce

We've needed a rather large space to reproduce this, I don't know exactly when this becomes an issue but this is a space with 1,822 records. This takes several seconds when a new environment is created to go from "In Progress" to "Complete" before it's ready to have migrations run on it.

**Comment by TimBeyer** [comment]
This tool has no `createEnvironmentFromId` function or anything like it.  
It really only applies content type and entry updates to an already existing environment.  
Could it be that you are using a third party wrapper around this?

**Comment by loremipson** [comment]
Yes, my mistake. I'm using `contentful-migration` along with `contentful-management`, `createEnvironmentFromId` is actually a part of `contentful-management`. I'll recreate this over there.

**Comment by loremipson** [comment]
For reference, here's the new issue: https://github.com/contentful/contentful-management.js/issues/386
