### ISSUE TITLE
Support changeFieldControl for apps

### ISSUE THREAD

**Issue by electriccode** [contentful/contentful-migration#471]
## Expected Behavior
`changeFieldControl` should accept `widgetNameSpace` as `app`. As per [it's type definition](https://github.com/contentful/contentful-migration/blob/bd335d87dd4275b11fceb53954969e3e301d4cf4/index.d.ts#L180), for `widgetNamespace` it accepts `builtin` or `extension`. It should also support `app` value, so that it can be used like this
```
contentModel.createField('image', {
    name: 'Image',
    type: 'Object',
    required: true,
  })
contentModel.changeFieldControl('image', 'app', 'cloudinary')
```

## Actual Behavior

As of now passing this parameter as `app` doesn't link the field with app.

![image](https://user-images.githubusercontent.com/1471581/90399495-a8463880-e0b8-11ea-93dd-db0e29f1c6cd.png)

## Steps to Reproduce

1. Assuming you have a free account, install Cloudinary app
2. Configure contentful-cli and create a migration to create a content model named `ImageCard` with fields `title` and `image`, both required. Sample migration specified below
3. Pay attention to 2nd last line where I change the appearance of field to cloudinary type. Same thing can be done via UI, sample image below

Sample Migration
```
module.exports = function (migration, context) {
  const contentModel = migration.createContentType('ImageCard', {
    name: "Image Card",
    description: "Image card with title and image",
    displayField: "title",
  });
  contentModel.createField('title', {
    name: 'Title',
    type: 'Symbol',
    required: true,
  })
  contentModel.createField('image', {
    name: 'Image',
    type: 'Object',
    required: true,
  })
  contentModel.changeFieldControl('image', 'app', 'cloudinary')
}
```

This can be done via UI
![image](https://user-images.githubusercontent.com/1471581/90399902-54881f00-e0b9-11ea-8670-98f1f933aaef.png)

## Context

I was creating content models using migrations and I came across a scenario where I needed fields whose appearance is configured by Cloudinary app.

## Environment

-   **Node Version**: 10.15.3 
-   **Package Manager Version**: `1.17.3` `yarn -v` 
-   **Operating System**: arwin C02XP20RJG5H 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64 
-   **Package Version**: Not sure, though `contentful -v` outputs `1.4.24`

**Comment by electriccode** [comment]
I resolved this by changing this line
`contentModel.changeFieldControl('image', 'app', 'cloudinary')`
to
`contentModel.changeFieldControl('image', 'app', 'some-random-string-which-is-actual-widget-id')`

The thing is this widget id is unique per install and the only way to get that is create the content model using UI having this field and then creating a dump from cli. Can we at least make this widget id more obvious and also add an example in docs?

**Comment by Jwhiles** [comment]
Hey @electriccode 

You can use the app_installations endpoint to get the id that you need. Note that for apps, the definition id is the widget id. 

```js
const contentful = require("contentful-management");

module.exports = async function (migration, context) {
  const contentModel = migration.createContentType("ImageCard", {
    name: "Image Card",
    description: "Image card with title and image",
    displayField: "title",
  });

  contentModel.createField("title", {
    name: "Title",
    type: "Symbol",
    required: true,
  });

  contentModel.createField("image", {
    name: "Image",
    type: "Object",
    required: true,
  });

  // Request all app installations
  const appInstallations = await context.makeRequest({
    method: "GET",
    url: `/app_installations`,
  });
  
  // Find the appDefinition with the name `Cloudinary` and use its ID
  const cloudinaryId = appInstallations.includes.AppDefinition.find(appDefinition => {
    return appDefinition.name === "Cloudinary";
  }).sys.id;

  contentModel.changeFieldControl("image", "app", cloudinaryId);
};
```

**Comment by electriccode** [comment]
@Jwhiles Can the typings be updated for the same? As of now I get this error,

`Argument of type '"app"' is not assignable to parameter of type '"builtin" | "extension"'.ts(2345)`

![image](https://user-images.githubusercontent.com/1471581/91153490-e6a5ae00-e6dd-11ea-9dee-77164bed6aa9.png)
