### ISSUE TITLE
Editor Interface support

### ISSUE THREAD

**Issue by cachrisman** [contentful/contentful-migration#57]
When creating or editing a content type, is there a way to set the editor interface using this tool?

**Comment by thebiglabasky** [comment]
This is a frequent request that is logged in our backlog but we don't have immediate plans for that.

**Comment by monkseal** [comment]
Looks like work has already begun #58, this will be a great addition.

**Comment by coffeepunk** [comment]
@cachrisman using the binary in the latest build available in master you can use `changeEditorInterface` to change the Editor Interface when using `createContentType` and `editContentType` like this.

```
module.exports = function(migration) {
    const gm = migration.createContentType('genericModel', {
        name: 'Generic model',
        description: 'Radio buttons for selecting country'
    });
    gm.createField('region', {
        name: 'Country',
        type: 'Symbol',
        required: true,
        validations: [{'in': ['SE', 'DK', 'NO']}]
    });
    gm.changeEditorInterface('region', 'radio');
};
```
When using `changeEditorInterface` with `editContentType` it alls seems a bit unstable at the moment. When editing a Content Model and creating a field the `changeEditorInterface` makes the migration halt with a "batch" error, but creates the field in question.

Running a migration with only `changeEditorInterface` like this works and I've not run into any issues yet.

```
module.exports = function(migration) {
    const gm = migration.editContentType('genericModel');
    gm.changeEditorInterface('myField', 'radio');
};
```

This only works with the latest code from this repo, not the latest NPM version.

**Comment by zcei** [comment]
> When editing a Content Model and creating a field the changeEditorInterface makes the migration halt with a "batch" error, but creates the field in question.

Thanks for noticing @coffeepunk - I could reproduce the issue locally, and will try to come up with a fix prior to the next release.

**Comment by aghuddleston** [comment]
Very much looking forward to this feature.

**Comment by Khaledgarbaya** [comment]
This feature was added on v 0.9.0
