### ISSUE TITLE
updateReferences  in transformEntriesToType wont unlink entry

### ISSUE THREAD

**Issue by snovos** [contentful/contentful-migration#584]
When trying to delete entry that is already linked, it fails with **shouldPublish** flag set to `true`.
Reason: Entry gets deleted but link is still there

## Expected Behavior

Remove link from deleted entry

## Actual Behavior

_ENTRY IS MISSING OR INACCESSIBLE_ message appears

-   **Node Version**: 14
-   **Package Manager Version**: yarn
-   **Operating System**: MacOS
-   **Package Version**: ^1.6.0

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.
