### ISSUE TITLE
Where is the changelog for versions after 0.12.3?

### ISSUE THREAD

**Issue by janaagaard75** [contentful/contentful-migration#614]
`CHANGELOG.txt` only contains changes up to version 0.12.3. Is there somewhere else, where I can find the changes made since that version?

I am currently using version 1.6.2 and would - of course - very much like to update to the latest version, but without a changelog, I can't assess how difficult at task this is.

If the answer is that the changelog simply hasn't been maintained then fair enough, but if so, I I think this deserves to be mentioned in the changelog.

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.
