### ISSUE TITLE
runMigration doesn't support typescript files as input

### ISSUE THREAD

**Issue by phawxby** [contentful/contentful-migration#633]
## Expected Behavior

Something like the following should execute.
```
      const config: RunMigrationConfig = {
        filePath: 'someFilePath.ts',
        spaceId,
        environmentId,
        accessToken,
      };

      await runMigration(config);
```

## Actual Behavior

```
The contentful-schema/1/00-languages.ts script could not be parsed, as it seems to contain syntax errors.

contentful-schema/1/00-languages.ts:1
import { MigrationFunction } from 'contentful-migration';
^^^^^^
```

## Context

Trying to run multiple migration files in sequence based on various rules. It makes sense to use runMigration rather running command line calls from within a ts script. 

## Environment

Node Version: 12.19.0
"contentful-migration": "^4.0.6",

**Comment by grgur** [comment]
I ran into the same thing and ended up writing a script that executes `tsc` with a custom `tsconfig.json` just for migration scripts. `tsc` is sequenced just before the migration cli.

Nonetheless, automatic TS compilation (similar to what webpack does with loaders) would be a great feature to have

**Comment by arminrosu** [comment]
@phawxby I'm just running everything through `ts-node`, no compilation required and it loads typescript files without issue.

e.g. `ts-node migration.ts` where migration.ts is:

```ts
import { runMigration } from 'contentful-migration';

//...

await runMigration({
  filePath: 'someFilePath.ts',
  spaceId,
  environmentId,
  accessToken,
});
```

**Comment by Swissbite** [comment]
@arminrosu 's solution works on our system.

I can confirm that it works with `ts-node`, the current released version of `contentful-migration` and latest LTS Version of node.js

**Comment by OriginalEXE** [comment]
For anyone getting a `TypeError: migrationCreator is not a function` error, make sure you use `module.exports` instead of `export default`. This is what your migration file would look like:

```ts
import { MigrationFunction } from "contentful-migration";

const migrate: MigrationFunction = (migration) => {
  
};

module.exports = migrate;
```

**Comment by tomardern** [comment]
I'm getting the same error as @phawxby:

`Error: The migration script could not be parsed, as it seems to contain syntax errors.`

@arminrosu Please can you share your tsconfig.json file?

**Comment by arminrosu** [comment]
@tomardern was asking about my tsconfig, but I suppose by the time I got to respond he figured it out and edited the comment (sorry for the late response). In case anyone else has issues, this is my tsconfig.json, fairly basic:

```json
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "compilerOptions": {
    "declaration": true,
    "esModuleInterop": true,
    "lib": ["ES2020"],
    "module": "CommonJS",
    "moduleResolution": "node",
    "noImplicitAny": false,
    "outDir": "dist",
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "strict": true,
    "target": "ES2020",
    "types": ["node"]
  },
  "exclude": [],
  "include": ["src/**/*"]
}
```

**Comment by tomardern** [comment]
My initial guess was that my `tsconfig.json` was incorrect... After an hour or so of debugging, I realised it needed the absolute path, and edited my comment. Thanks @arminrosu - this might be useful for other developers who are having the same problem. 👍

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.
