### ISSUE TITLE
[Bug] Migration fails when content model has existing regex validations without flags

### ISSUE THREAD

**Issue by PepperTeasdale** [contentful/contentful-migration#64]
I have a straightforward migration I'm trying to run to add a field to a content type.
```javascript
module.exports = function (migration) {
     const page = migration.editContentType('article');

    page.createField('stickyCTANavBar')
      .type('Link')
      .linkType('Entry')
      .name('Sticky CTA Nav Bar')
      .validations([{ linkContentType: ['ctaConfig'] }])
 };
```

The output when I run it:
```
Publish Content Type article
Update Content Type financialAdvisorLandingPage

  Create field stickyCTANavBar
    - type: "Link"
    - linkType: "Entry"
    - name: "Sticky CTA Nav Bar"
    - validations: [{"linkContentType":["ctaConfig"]},{"flags":""}]


Error: "flags" validation expected to be "string", but got "null"
```

I have tried removing the content type validation, but I still get this error. Parsing through the documentation, I see there is a flag parameter for regex validations, but I'm not doing any regex validations on this field. If there is something wrong with the content model's other fields, it is not noticeable from the Contentful UI, since the model seems to be valid and working as expected. Any ideas?

**Comment by PepperTeasdale** [comment]
I'm seeing that my content model has another field with a regex validation with no flags. The flags are not required in contentful-ui, perhaps they shouldn't be here either?

**Comment by hugoduraes** [comment]
I'm also getting this error while trying to add a new field to an existing content type.

```js
module.exports = function (migration) {
  const contentType = migration.editContentType('contentTypeId');

  contentType.createField('fieldId', {
    name: 'Field Name',
    type: 'Integer',
    required: true,
    localized: false
  });
};
```

Getting error `Error: "flags" validation expected to be "string", but got "null"`.
