### ISSUE TITLE
Migrations should roll back on error

### ISSUE THREAD

**Issue by arminrosu** [contentful/contentful-migration#645]
Hello,

I'm using `transformEntriesToType` to migrate some entries across types. 

My source entry type contains an optional field, which in the target is required. 

The migration transforms the entries, but fails at the publishing step, since the required fields are not present.

## Expected Behavior

Roll back _all changes_ if any step fails.

## Actual Behavior

```bash
Migrate entries from article
  - from: article
  - to: webPage
  ❯ Migrate entries from article
  ❯ Migrate entries from article
    ✖ Making requests (151/151)
      → Batch failed
🚨  Migration unsuccessful
Batch failed

Error: {"status":"Unprocessable Entity","message":"Validation error","details":{"errors":[{"name":"required","path":["fields","slug"],"details":"The property \"slug\" is required here"},{"name":"required","path":["fields","variant"],"details":"The property \"variant\" is required here"}]},"url":"spaces/[spaceId]/environments/master/entries/[entryId]/published"}

```

## Possible Solution

This specific error can be fixed by validating the source content against the target rules if `shouldPublish: 'preserve',` or `shouldPublish: true,` is set on the `transformEntriesToType` options.

## Steps to Reproduce

1. Create contentType `article` with `fields.title` and `fields.slug` optional
2. Create an entry, make sure `fields.slug` is not set
3. Create contentType `page` with `fields.slug` required
4. Run:

```js
migration.transformEntriesToType({
  sourceContentType: 'article',
  targetContentType: 'page',
  from: ['title', 'slug'],
  shouldPublish: 'preserve',
  updateReferences: true,
  removeOldEntries: true,
  identityKey: function (fields) {
    const value = fields.title['en-US'].toString();
    return MurmurHash3(value).result().toString();
  },
  transformEntryForLocale(fromFields, currentLocale) {
    return Object.fromEntries(Object.keys(fromFields).map((key) => [key, fromFields[key][currentLocale]]));
  },
});
```

## Context

The migration doesn't roll back the changes, even though the migration fails. Now I no longer have a way of checking which entries were actually published beforehand.

Of course this wasn't against `master`, so I can add checks and fixes before the migration. Still not fun.

## Environment

-   **Node Version**: v14.8.0
-   **Package Manager Version**: npm 6.14.7
-   **Operating System**: Darwin my-hostname 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64
-   **Package Version**: 4.0.6

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.
