### ISSUE TITLE
requestBatchSize doesn't work

### ISSUE THREAD

**Issue by greatgumz** [contentful/contentful-migration#682]
## Expected Behavior

```
contentful space migration --request-batch-size '1' migrations/01-magical-blogpost-migration.js
```

If I have 300 blogPost content models this should only run 1 time.

## Actual Behavior

All 300 blogPost content models are being updated.

## Possible Solution

Add property that enables Migration CLI to take request batch size parameter to be set

## Context

I want test a single entry live so I can see a single result or perhaps target a specific blogPost with a certain ID or parameter.

## Environment

-   **Node Version**: 14.15.4
-   **Package Manager Version**: 6.14.10
-   **Operating System**: macOS Catalina (10.15.7)
-   **Package Version**: 4.0.9

**Comment by marcolink** [comment]
Hi @greatgumz,

`requestBatchSize` is [limiting the number of entries](https://github.com/contentful/contentful-migration/blob/master/src/lib/fetcher.ts#L185) requested per batch request (entries collection endpoint). 
 This can help in situations, where the response size is exceeding the [limits](https://www.contentful.com/developers/docs/technical-limits/). 

This parameter can not be used to selectively operate on a single entry.
Migrations for entries are usually meant to operate on all content entries for a specific content type.  

I'd be curious to better understand your use. case? Is this only meant for testing purposes? 

Best
Marco

**Comment by greatgumz** [comment]
Yup this was for testing
