### ISSUE TITLE
Include the content type ID in the validation message when trying to edit a field that doesn't exist

### ISSUE THREAD

**Issue by KennethSundqvist** [contentful/contentful-migration#690]
I'm using a loop to update the same (reusable) field on many content types at once, and apparently some of these content types don't have that field (our own mistake), and the validation message doesn't help me understand which content type it is, so I have to go through 34 content types manually to figure out which 4 of them are missing the field.

The validation messages look like this in the console (stack traces removed):

```
Line 23: You cannot edit field "contentfulTitle" because it does not exist.
Line 23: You cannot edit field "contentfulTitle" because it does not exist.
Line 23: You cannot edit field "contentfulTitle" because it does not exist.
Line 23: You cannot edit field "contentfulTitle" because it does not exist.
```

It would be helpful if the message included the content type ID, like the message does when you try to edit a field on a content type that doesn't exist:

```
Line 23: You cannot edit field "contentfulTitle" on content type "webPagee" because it does not exist.
Line 23: You cannot edit field "contentfulTitle" on content type "webSectionn" because it does not exist.
```

The new validation message could be:
```
You cannot edit field "${id}" because it does not exist on content type "${ctId}"
```

Would also be useful to have this in the validation message when trying to delete a field that's already been deleted, when updating multiple content types in the same migration script:

https://github.com/contentful/contentful-migration/blob/00c988245000c95a10d3620c123c7d72182e7e40/src/lib/migration-chunks/validation/errors.ts#L42-L52

## Environment

-   **Package Version**: 4.0.6

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.
