### ISSUE TITLE
Parameter "shouldPublish" of "deriveLinkedEntries" method should allow "preserve" value.

### ISSUE THREAD

**Issue by wiktor-mazur** [contentful/contentful-migration#691]
## Expected Behavior

Parameter `shouldPublish` of `deriveLinkedEntries` method should allow `preserve` value just like in `transformEntriesToType` method.

It would also be convenient to be able to make this decision conditionally for each processed entry.

## Actual Behavior

Currently the `deriveLinkedEntries` either publishes drafts as a side effect or leaves every entry "changed".

**Comment by marcolink** [comment]
A fix has been released - closing this for now

**Comment by wiktor-mazur** [comment]
Thanks!
