### ISSUE TITLE
Provide "real" programmatic way to use this library

### ISSUE THREAD

**Issue by szimek** [contentful/contentful-migration#70]
First, thanks a lot for creating this library!

I'd like to keep track of which migrations were already executed, so that someone doesn't accidentally execute the same migration twice. For this I want to use https://github.com/tj/node-migrate. In the [Programmatic Usage](https://github.com/contentful/migration-cli#programmatic-usage) section it still says to use the CLI, but with `--yes` option. It means that I'd have to run it as a system command, instead of simply calling a library function.

Other Contentful libraries like `contentful-import` and `contentful-export` provide programmatic usage, so are there any plans to add it to this library as well? I'm not sure if if it would work, but maybe it would be enough to change `run` function in `/src/bin/cli.ts` to accept `options` param, move it to another file that would export it and then update `/src/bin/cli.ts` to import it and call it with `argv` argument.

**Comment by thebiglabasky** [comment]
Hi,

Thanks for your feedback.

That's indeed part of the plan to make it a library and integrate it into the [contentful-cli](https://www.npmjs.com/package/contentful-cli).
There's no timeline for that yet.

We are also received a lot of feedback to actually keep track of migrations that were run. This would be something we'd like to do on the server-side ideally, but is not planned either for the moment.

As soon as things evolve on both topics, we'll update this issue.

**Comment by Khaledgarbaya** [comment]
Hey @szimek,
you can use the library as a library https://github.com/contentful/contentful-migration#usage-as-a-library
