### ISSUE TITLE
`addSidebarWidget` types don't match the JSDoc

### ISSUE THREAD

**Issue by AndrewLeedham** [contentful/contentful-migration#709]
## Expected Behavior

Types to match the JSDoc

## Actual Behavior

https://github.com/contentful/contentful-migration/blob/bbaeb6c573f9387060f535d2738181d8a363bee7/index.d.ts#L221 states the 4th parameter `insertBeforeWidgetId` can be null. But the types on accept a string: https://github.com/contentful/contentful-migration/blob/bbaeb6c573f9387060f535d2738181d8a363bee7/index.d.ts#L226

## Possible Solution

To me it seems like the definition should be:
```
 addSidebarWidget (widgetNamespace: 'sidebar-builtin' | 'extension',
                    widgetId: string,
                    settings?: ISidebarWidgetSettings,
                    insertBeforeWidgetId?: string | null): void
```
Making both `settings` and `insertBeforeWidgetId` optional as well as `null` accepted for `insertBeforeWidgetId`.

## Steps to Reproduce

N/A

## Context

N/A

## Environment

-   **Node Version**: 14.16.0
-   **Package Manager Version**: 6.14.11
-   **Operating System**: Darwin Andrews-Work-MacBook-Pro.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
-   **Package Version**: 4.1.0

**Comment by marcolink** [comment]
closing this for now as a fix has been released https://github.com/contentful/contentful-migration/pull/888#issuecomment-919948868
