### ISSUE TITLE
Support field help text

### ISSUE THREAD

**Issue by walwoodr** [contentful/contentful-migration#73]
It would be great to be able to set help text on a field in migrations. Documentation and a code search suggests this is not currently possible.

**Comment by thebiglabasky** [comment]
It is but not documented properly unfortunately (I'll file a ticket to fix that)
Here's a sample payload which achieves this (the `helpText` is defined within the `settings` of the editor interface control definition):

```
{
  "sys": {
    ...
    },
    "contentType": {
      "sys": {
        ...
      }
    }
  },
  "controls": [
    {
      "fieldId": "slug",
      "widgetId": "slugEditor",
      "settings": {
        "helpText": "Slug used for URLs"
      }
    }
  ]
}
```

**Comment by gburgett** [comment]
Now that editor interfaces can be changed via the migration CLI, this is the last missing piece for us.  This is our only remaining manual task after running migrations.

**Comment by thebiglabasky** [comment]
This PR adds support for settings including help text and enabling bulk editing:
https://github.com/contentful/contentful-migration/pull/97
