### ISSUE TITLE
Errors currently obfuscate true source of problems

### ISSUE THREAD

**Issue by phawxby** [contentful/contentful-migration#730]
These custom errors are extremely unhelpful when trying to diagnose the source of issues because you cannot see the actual error that was thrown. Perhaps it was a connectivity issue or some other problem unrelated to the "helpful" message. 

https://github.com/contentful/contentful-migration/blob/168c7f2c02aab2caa3ac595c2dd136e2ed7609a0/src/lib/migration-parser.ts#L83
https://github.com/contentful/contentful-migration/blob/168c7f2c02aab2caa3ac595c2dd136e2ed7609a0/src/lib/migration-parser.ts#L113
https://github.com/contentful/contentful-migration/blob/168c7f2c02aab2caa3ac595c2dd136e2ed7609a0/src/lib/migration-parser.ts#L126

**Comment by theshortcut** [comment]
we ran into this as well, the underlying error was due to request size (were getting a 400 request too big error)
