### ISSUE TITLE
Support field appearance

### ISSUE THREAD

**Issue by walwoodr** [contentful/contentful-migration#74]
Would be excellent to be able to set the appearance on a field type to one of the default appearance types for that content type -- ie dropdown/radio/single-line for Symbol.

**Comment by thebiglabasky** [comment]
This is now supported in the latest version of the Contentful CLI (0.12.0

**Comment by Jimmydalecleveland** [comment]
I've looked through the CHANGELOG.md and releases tab, as well as the README and have not found documentation on how to change appearance per field. Could you link me to an example?

**Comment by phoebeschmidt** [comment]
@Jimmydalecleveland it used to be called 'changedEditorInterface' but now it's called 'changeFieldControl'. You can see an example here https://github.com/contentful/contentful-migration/blob/master/examples/16-change-field-control.js

**Comment by Jimmydalecleveland** [comment]
Thank you very much, I was looking in the definitions for `createField` but that makes sense.
