### ISSUE TITLE
a simple way to add to a validations array

### ISSUE THREAD

**Issue by aleks-dfds** [contentful/contentful-migration#76]
Need a way to add a new row to a validation. 

Currently if i want to add a new entry in the validations array, the code looks like this:

`dynamicContentRowType.editField(
    'contentEntry',
    {
      "name": "Content entry",
      "type": "Array",
      "localized": false,
      "required": true,
      "validations": [],
      "disabled": false,
      "omitted": false,
      "items": {
        "type": "Link",
        "validations": [
          {
            "linkContentType": [
              "type0",
              "type1",
              "type2",
              "type3",
              "type4",
              "type5",
              "type6",
              "type7",
              ...
              "type50" //you get the picture!
            ]
          }
        ],
        "linkType": "Entry"
      }
    }`

This cumbersome syntax makes it tricky to keep track of what the change actually was and hard to debug. So the ideal scenario would be:
`dynamicContentRowType.editField('contentEntry').items.addValidation('type55');`

**Comment by weotch** [comment]
Here's my migration script for adding a new allowed link, would be great if there was a built in one-liner for this:

```js
module.exports = async (migration, { makeRequest }) => {

    // Settings
    const typeName = 'contentPage',
        linkingField = 'contentBlocks',
        newlyAllowedType = 'marquee'

    // Get the list of current linkContentType values
    const schema = await makeRequest({
        method: 'GET',
        url: `/content_types?sys.id[in]=${typeName}`
    })

    // Add marquee to the list of allowed content types
    const validations = schema.items[0].fields
        .filter(field => field.id == linkingField)[0]
        .items.validations.map(rule => {
            if (rule.linkContentType &&
                !rule.linkContentType.includes(newlyAllowedType)) {
                rule.linkContentType.push(newlyAllowedType)
            }
            return rule
        })

    // Update the link validation
    migration.editContentType(typeName)
        .editField(linkingField).items({
            type: 'Link',
            linkType: 'Entry',
            validations: validations,
        })
};
```

**Comment by alan-nakagiri** [comment]
Has this functionality been added to the Contentful Migration API?

I second this would be a nice to add or remove contentTypes to the validation rule in a more straightforward way.

**Comment by shaungcheng-asana** [comment]
Want to bump this issue up as well! This is the first GitHub issue coming up in google search result. We also have this use case of removing/adding a type to validations linkContentType. Is there any update on this issue? 

I have yet to find similar functionality in the [Contentful doc: Content type / Validations](https://www.contentful.com/developers/docs/references/content-management-api/#/reference/content-types/content-type). Currently the doc seems to suggest hardcoding the list of validations `linkContentType`. This could be hard to keep track of and maintain as the list item changes over time by multiple places:

> To remove a specific validation, update the content type leaving that validation out of the field's validations collection. To remove all the validations applied to a field, update the content type schema removing the validations property.

Seems unfortunately https://github.com/contentful/contentful-migration/pull/66 @thebiglabasky mentioned is determined not merged in at the end. I thought this functionality of only needing to specify the type to be added/removed would be a fairly common use case and should benefit many other Contentful SDK users.

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.
