### ISSUE TITLE
Suggestion: Include Predicate for setTagsForEntry

### ISSUE THREAD

**Issue by nteague22** [contentful/contentful-migration#804]
## Expected Behavior

To have two additional, optional parameters added to MigrationFunction.setTagsForEntry:

predicate: optional QueryOptions style predicate for applying a filtered tag set, or the visibility of the sys property at readonly level.  This would enable the function to not only set the tags for the entry based on content fields, but where it effects a change to a published item, it would be much more helpful to not change an item already changed or not yet published.

the shouldPublish option:  All other migration transforms for entry scope, allow the passing of the shouldPublish option -- this would enable within a migration call the ability to set tag(s) and publish if previously isPublished() and not isUpdated(), or leave as changed if the other statuses.

## Actual Behavior

Currently there are no options for these workflows, so to use the CMA and add tags requires I use migrations that are efficient, validate, etc. and mix with manual code of creating the client, getting the contentType and reading entries on a filter to track status on before and after the migration.  This is both tedious/inefficient as well as hazardous -- since the calls outside of migration do not get validated | dry-ran or aborted.  Also a broken operation midway through is much less resilient outside of the migrations DSL.

## Possible Solution

Add the parameters, the basic flow should be similar to the transformEntriesForType and the deriveLinkedEntries calls.  The predicate is something that would require exposing the metadata, maybe an optional parameter to fields called metadata, for reading entry by entry status

## Context

Affects my development of effective and idempotent contentful migrations at my current occupation

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.
