### ISSUE TITLE
Typings for unique validation wrong

### ISSUE THREAD

**Issue by phawxby** [contentful/contentful-migration#805]
## Expected Behavior

Being able to use the migrations API to remove unique field validation

## Actual Behavior

It doesn't work, the typings require unique to be `true` or `undefined`, when set to undefined the payload sent to Contentful has the validation removed.

```
.validations([{ unique: undefined }]);
```

Gets sent as 
```
"[{}]"
```

## Possible Solution

```
.validations([{ unique: false as any }]);
```

Change `true` to `boolean` here.
https://github.com/contentful/contentful-migration/blob/4b9dcae0e7616da9153d0fa481871978595049e7/index.d.ts#L97

**Comment by smorris-youfoodz** [comment]
I wasted a chunk of time today trying to get this working, trying to diagnose "too few properties provided", only to discover it's a defect.  

The JS docs point us towards 
https://www.contentful.com/developers/docs/references/content-management-api/

The Validation section at 
https://www.contentful.com/developers/docs/references/content-management-api/#/reference/content-types/content-type
says... 

> To remove a specific validation, update the content type leaving that validation out of the field's validations collection. To remove all the validations applied to a field, update the content type schema removing the validations property.

... but alas, "too few properties"

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.
