### ISSUE TITLE
[Suggestion] Add an option to delete all existing entries to deleteContentType method

### ISSUE THREAD

**Issue by aladage** [contentful/contentful-migration#852]
This is a request to add a `deleteExistingEntries` (boolean) option to the `deleteContentType` method. This option should default to `false` to prevent accidental content deletion.

Currently, if the `deleteContentType` method is executed on an environment and an entry is present, an error will be thrown and the migration will fail. Because we're using multiple Contentful environments and have automated migration scripting as part of our CI/CD workflows, this scenario will cause an entire deployment to fail, and can only be resolved by manually visiting all environments and deleting all entries before the CI/CD process has run.

**Comment by pascaloliv** [comment]
It sounds to be an interesting idea.👍🏻

**Comment by bradley-varol** [comment]
Needed exactly this today!

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.
