### ISSUE TITLE
derivedLinkedEntries requiring identityKey function

### ISSUE THREAD

**Issue by eujinkim** [contentful/contentful-migration#86]
I am trying to refactor an existing content model by
* factoring out some of the fields in the model to a new content type
* create a new entry of the new content type per existing entry
* link those two

In order to achieve this, I was using https://github.com/contentful/migration-cli#derivelinkedentriesconfig. The issue I found was that `identityKey` function was required.

If I use `derivelinkedentries` like the example, I'd lose the auto-generated entry id like the rest of the entries have. I'm worried that this will lead to the same entry id at some point and the best way to avoid this to rely on https://www.contentful.com/developers/docs/references/content-management-api/#/reference/entries/entries-collection/create-an-entry/console/js. So I believe there should be an option to use auto-generated entry id when creating a new entry from an existing entry.

**Comment by Khaledgarbaya** [comment]
Hi @eujinkim,
You can use a hash function to generate the ids from the content of the field.

**Comment by eujinkim** [comment]
Hi @Khaledgarbaya, could you show an example of doing so?
My goal is to avoid any potential clashes of ids.

Also, I am currently doing a workaround to get an auto-generated id using `makeRequest`

```
    identityKey: async (fromFields) => {
      // Create an entry to get the auto-generated id using management API
      const entry = await makeRequest({
        method: 'POST',
        url: `/entries`,
        data: {},
        headers: {
          'X-Contentful-Content-Type': 'someContentType'
        }
      })

      // The implementation of deriveLinkedEntries skips running deriveEntryForLocale
      // when an entry with the given id already exists
      // - https://github.com/contentful/contentful-migration/blob/71864677d2935b66841b27a0a8e4e31f3880b49d/src/lib/action/entry-derive.ts#L74#L97
      // To get around this, we save the entry id, delete the entry and return the saved entry id
      const deleteEntry = await makeRequest({
        method: 'DELETE',
        url: `/entries/${entry.sys.id}`,
      });

      return entry.sys.id;
    },
```

**Comment by Khaledgarbaya** [comment]
hey @eujinkim,
you don't need to create an entry to get the id you can use a library like [uuid62](https://github.com/shanehughes3/uuid62) to generate an id similar contentful's id.

```js
identityKey: (fromFields) => {
     const uuid = uuid62.v4();
// -> 2qY9COoAhfMrsH7mCyh86T

// decode a base-62 uuid
const originalUUID = uuid62.decode(uuid);
// -> 9af099b2-6244-4fc1-b72b-1d69a24481b7

// base-62 encode an existing traditional uuid
const encoded = uuid62.encode('8fc60e7c-3b3c-48e9-a6a7-a5fe4f1fbc31');
// -> 2fNwVYePN8WqqDFvVf7XMN
return encoded
},
```
the idea behind `identityKey` is to avoid duplicate entries, so that multiple source entries can link to the same derived entry
