### ISSUE TITLE
Migration script fails at validation trying to deleteField and createField when content type has 50 fields

### ISSUE THREAD

**Issue by kovalyovi** [contentful/contentful-migration#886]
## Expected Behavior
We have a Content type that already has 50 fields. In my script, I first delete some of the fields (8 fields) and then create other fields and add them to this Content type. The script should pass the built-in validation and do the migration. I have to stick with `module.exports` migration.

## Actual Behavior
When I run the `contentful space migration` script on the file, it gives the validation error `Content type "reservationPage" cannot have more than 50 fields`. It shouldn't happen since when the script actually runs, it publishes changes after each content type update, thus there won't be more than 50 fields in my case (I delete 8 fields and add 3 afterward).

## Possible Solution
The built-in validation needs to check for the max number of fields including deleting fields for that Content type.

## Steps to Reproduce
 
 1. Create a content model with 50 fields and publish it (let's say its name is `reservationPage`)
 2. Write a script similar to the following
 ```
module.exports = function (migration) {
  const reservationPage = migration.editContentType('reservationPage');

  reservationPage.deleteField('existingField49');
  reservationPage.deleteField('existingField50');

  reservationPage.createField('newField1');
  reservationPage.createField('newField2');
}
 ```
3. Run script `contentful space migration -e <Environment> <File path>`
4. Encounter the following error: `Error: Content type "reservationPage" cannot have more than 50 fields.`

## Context
In order to achieve the needed result, I had to break down migration into 2 separate files (let's say `migration-1.js` and `migration-2.js` which is not the best solution for our use. Our goal is to be possible to delete and create fields within the same migration script for fields that reach the capacity limit of 50 fields.

## Environment

-   **Node Version**: v14.16.1
-   **Package Manager Version**: 6.14.11
-   **Operating System**: Windows 10 20H2 x64 (OS Build 19042.985)
-   **Package Version**: 4.5.0 (contentful-migration package)

**Comment by kovalyovi** [comment]
Following up on the issue

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.
