### ISSUE TITLE
`addSidebarWidget` WidgetNamespace does not support 'app' namespace

### ISSUE THREAD

**Issue by prkirby** [contentful/contentful-migration#887]
## Expected Behavior

https://github.com/contentful/contentful-migration/blob/f7c789a4d400923e874cf15130ddd28adc9e9606/src/lib/entities/content-type.ts#L185

When trying to add a sidebar that is exposed by an app, I cannot use the namespace 'app' as you can with `configureEntryEditor`

## Possible Solution

`addSidebarWidget (widgetNamespace: 'sidebar-builtin' | 'extension' | 'app',`

## Context
I cannot currently add a sidebar widget to ContentType that is exposed from the Optimizely App via migration

**Comment by marcolink** [comment]
@prkirby We just released a fix for that
https://github.com/contentful/contentful-migration/pull/885#issuecomment-919948832
