### ISSUE TITLE
"defaultValue" is not a valid property name for a field.

### ISSUE THREAD

**Issue by galihariad** [contentful/contentful-migration#909]
## Expected Behavior

I ran `contentful space migration` for this sample file: [32-create-fields-with-default-values.js](https://github.com/contentful/contentful-migration/blob/master/examples/32-create-fields-with-default-values.js) in my terminal to my contentful environment. I assume it should be working fine, since it is the sample file for updating `defaultValue` from migration script.

## Actual Behavior

When I ran the file, it is said that _"defaultValue" is not a valid property name for a field._.

## Steps to Reproduce

1. From terminal, I ran this command: 
`contentful space migration --space-id <space-target> --environment-id <env-target> --management-token <CMA-token> <directory to 32-create-fields-with-default-values.js>`
2. This is what always appears in my terminal:
![image](https://user-images.githubusercontent.com/72022491/135082409-9ce6d9b9-9e99-47d5-8a22-c5f7d8ebe04a.png)

## Context

I am trying to configure the default value of a boolean field, so whenever a new entry is created.. that boolean field will always be already set as TRUE by default.
So, users will only need to make update only whenever they need the boolean value to be FALSE.

## Environment

-   **Node Version**: v16.7.0
-   **Package Manager Version**: 7.20.3
-   **Operating System**: Darwin ip-192-168-1-9.ec2.internal 19.6.0 Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64 x86_64

**Comment by aglazyrin-mb** [comment]
Hi @galihariad !
Have you found a solution to this issue?
