### ISSUE TITLE
Add web app validations to migration cli

### ISSUE THREAD

**Issue by stefanjudis** [contentful/contentful-migration#91]
When defining short text validations in the CLI it would be great to provide the validations that are available in the web app.

<img width="811" alt="screen shot 2018-04-25 at 14 30 17" src="https://user-images.githubusercontent.com/962099/39245871-338f99a4-4895-11e8-9f25-d0429db30b9e.png">

Is this something we'd be up for providing?

**Comment by thebiglabasky** [comment]
I think that having validation building helper functions in general would be great to avoid having to replicate the expected API structure.
We discussed this back in the days but couldn't get there.

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.
