### ISSUE TITLE
Suggested changes to Usage as a library section in README

### ISSUE THREAD

**Issue by coffeepunk** [contentful/contentful-migration#92]
* The require should have .default as suffix to require the cli function properly or it will return `Error: Cannot find module 'contentful-migration-cli/built/bin/cli'`
* filePath option is misspelled, it says fielPath and that the file path works best when using an absolute path.
* The migration cli needs to be installed locally in the application or script folder node_modules directory. Which might be obvious, but since the main instruction is to install the migration cli globally it can be a bit misleading or cause confusion.

I suggest something like the following or similar.

### Usage as a library

Unless you have exported your NODE_PATH you need to have the contenful-migration-cli package installed locally in your application or script directory. Make sure your <migration-file-path> is relative to your file of execution.

```javascript
const path = require('path');
const runMigration = require('contentful-migration-cli/built/bin/cli').default
const options = {
  filePath: path.join(__dirname, '<migration-file-path>'),
  spaceId: '<space-id>',
  accessToken: '<access-token>'
}
runMigration(options)
```

**Comment by stefanzmindit** [comment]
Why not a PR for fixing this in readme? Randomly found this after 2hrs :D
