### ISSUE TITLE
Undefined environmentId is causing space and access error

### ISSUE THREAD

**Issue by coffeepunk** [contentful/contentful-migration#93]
When using the migration-cli as library you get the following error message, even if you have filled out both spaceId and accessToken.

```
The provided space does not exist or you do not have access.

🚨  Migration unsuccessful
```
Since the clientConfig object to the `createManagementClient` depends on the environmentId and it is not specified in the options object in the documentation I think a lot of people might be missing what's going on.

I suggest the following solutions.

1) Add the environmentId to the options object in the documentation.

```
const options = {
  fielPath: '<migration-file-path>',
  spaceId: '<space-id>',
  environmentId: '<environmentId (default is master)>',
  accessToken: '<access-token>'
}
```

2) or change the environmentId declaration to

`const environmentId = argv.environmentId || 'master'`

Both solution works, but I don't know which one is the best one and there might even be a third or fourth option since this have to do with future updates to Contentful space management.

**Comment by Khaledgarbaya** [comment]
this will be fixed in https://github.com/contentful/contentful-migration/pull/101
