### ISSUE TITLE
Not happy with the state of the documentation.

### ISSUE THREAD

**Issue by parkerhutchinson** [contentful/contentful-migration#935]
## Expected Behavior
I expect to find all the viable field information I need to create fields using the migration sdk. 

## Actual Behavior
Missing any information regarding assets. The `types` for `linkType` are incomplete. There are some special types that are not field types as the [documentation on the dotcom states](https://www.contentful.com/developers/docs/concepts/data-model/).

The examples are lacking field types and various validation gotchas. For instance, how does one work with Media? How do you reference multiple entry links? where is the API documentation for default data? How do you work with entry links where its only 1 possible entry type or an array of entry types? Im sure the information is buried deep into some example somewhere. Its just not well organized. The documentation for this repo needs an audit. Documentation should exist in one place. one. Not split between the dotcom and the repo. 

The interfaces are wrong.. `editField(id[, opts])` what is this saying?! coming from TS this would be an array of ids? id[, opt] this very non-standard. The interface should be `editField(id, [opts])`. is it written this way to show chaining? not obvious enough what the interface is implying. They are all like this.  why?

There's a whole other issue that I'm only going to mention here. Finding information on the site is very hard. the search feature seems to only bring up FAQ and Help Center documents. nextjs and reactjs documentation never has this issue when using their search. it's like you need to push the search into each category instead of searching the whole website.  

## Possible Solution

At other companies I've worked at they have a system known as AOR's (area of responsibility). There should be an AOR holder for documentation. 

The AOR core responsibilities should be: 

* quality
* coverage
* accessibility (how easy is it to find what you need as a developer)

All three are linked tightly around the developer experience.  From which im claiming is lacking. 

Let's look at two repos and their documentation. nextjs and reactjs, both repo's don't have documentation separated. They have one single location where documentation is found. They've chosen org/dotcom to hold that information. 

if you go to [nextjs repo](https://github.com/vercel/next.js/) do you find some documentation split out? no, you find links to nextjs.com where the documentation exists in **a single location.** If you go to [react's repo](https://github.com/facebook/react) do you find documentation in the repo split from the documentation on the org. again no, it's all pointing to the org where documentation exists in a single location.  

The coverage in both of those repo's is near 100% and there are code examples for almost every API. my guess right now based on a year's worth of working as an AOR holder for migrations at our company is that the docs for migrations are around 80% coverage. 

## Steps to Reproduce

These steps should be performed with someone who has no knowledge of the API. it'd be good to record their screen as well and see how they figure it out. 

1. try to figure out how to change how a widget is displayed
2. create a migration for image upload
3. create a migration for radio button field
4. create a migration for a field that allows 1 entry link to exist. make a migration for an array of entry links.

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.
