### ISSUE TITLE
Error: "changeEditorInterface" is not a valid property name for a content type.

### ISSUE THREAD

**Issue by a-lehdet** [contentful/contentful-migration#94]
Hi,

I'm unable to set editor interface via the `changeEditorInterface` method. Here's my code that adds a new field to an existing content model and attempts to change the editor interface for that field:

```
module.exports = function(migration) {

  const theme = migration.editContentType("theme");

  theme
    .createField("iabTier2")
    .name("IAB Tier 2")
    .type("Symbol")
    .localized(false)
    .required(false)
    .validations([
      {
        in: [
          "Action and Adventure Movies",
          "Adult Album Alternative",
          "Adult Contemporary Music"
        ],
        message: "Invalid value; not a predefined IAB Tier 2 category."
      }
    ])
    .disabled(false)
    .omitted(false);

  theme.moveField("iabTier2").afterField("iabTier1");
  theme.changeEditorInterface("iabTier2", "dropdown");

};
```

When I attempt to execute my migration script, I get the following error message:

```
"changeEditorInterface" is not a valid property name for a content type.
```

I have tried executing example scripts ([1](https://github.com/contentful/migration-cli/blob/master/examples/16-change-editor-interface.js), [2](https://github.com/contentful/migration-cli/blob/master/examples/17-change-editor-interface-for-existing-content-type.js)) and they both return the same error message.

My NPM version is 6.0.0. and `contentful-migration-cli` version is 0.7.0 on Mac OS X 10.10.5.

Any help would be greatly appreciated. 😄

**Comment by Khaledgarbaya** [comment]
Hi @a-lehdet,
We changed the library name on npm to `contentful-migration`.
can you `npm install -g contentful-migration` and try again

**Comment by a-lehdet** [comment]
Hi @Khaledgarbaya,

I did as you instructed and everything seems to be working now. I tested both setting the editor interface while creating a new content type as well as updating the editor interface on an existing content type.

On a related note, any plans to add support for setting help texts? That would be awesome.
