### ISSUE TITLE
[Suggestion] Allow makeRequest to work with non-environment endpoints

### ISSUE THREAD

**Issue by aghuddleston** [contentful/contentful-migration#942]
## Expected Behavior

Suggestion: I'd like to be able to add roles to a space via this migration framework.  

For example:
```
module.exports = async function (migration, { makeRequest }) {
  let role = await makeRequest({
    method: 'PUT',
    url: `/roles/developer-qa-role`,
    data: {
      "name": "Developer/QA",
      "description": "Allows reading Entries and managing API Keys",
      "policies": [...]
    }
  })
}
```

## Actual Behavior

Currently, when I try this I get a 404.  `makeRequests` generates the url as `spaces/XXXXX/environments/master/roles/developer-qa-role`, but the roles endpoint is not available on **environments**, only on **spaces**.

I tried not including an environment, but since the default is `master` and `createMakeRequest` forces the environment into the url, I can't get it to work at the moment.

## Possible Solution

A makeRequest that works on `spaces` and not just `environments`

## Context

We have many spaces with the same content model and use this library to roll the changes out to all the spaces.  I'd like to be able to roll changes such as creating roles out to all of our spaces w/our normal content model versioning strategy instead of needing one-off solutions.

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.
