### ISSUE TITLE
"makeRequest" does not wait for the user confirmation

### ISSUE THREAD

**Issue by alieslamifard** [contentful/contentful-migration#960]
Hello everyone,

Here is the scenario,
I created a migration in order to create a model and an entry out of it:
```javascript
// Step 1, Create the model
const dog = migration.createContentType('dog', {
  name: 'Dog'
});
const name = dog.createField('name');

// Step 2, Create an entry
const entry = await makeRequest({
  method: 'POST',
  url: `/entries`,
  headers: {
    'Content-Type': 'application/json',
    'X-Contentful-Content-Type': 'dog'
  },
  data: {
    fields: {
      name: {
        'de-DE': 'Big boy'
      },
    }
  }
});
```
The problem is, `makeRequest` doesn't wait for the first step ( that needs the user confirmation ) and runs immediately.

## Expected Behavior
Run the migration steps one by one in a sequence. (Just if the user confirmed it.)

## Actual Behavior
The first step in example waits for user confirmation, but the second step doesn't.

## Possible Solution

I think the `makeRequest` function is supposed to be used in other methods (e.g. deriveLinkedEntries) as a data/entry provider, not as the main script in migration. But from the API definition `This can be useful if you want to use API features that may not be supported by the migration object`, so it would be good to make it more migration-like.

## Steps to Reproduce

1. Follow the example and run it.
2. Confirm the migration in your CLI

## Environment

-   **Node Version**: 16.x.x
-   **Package Manager Version**: 7.10.0 
-   **Operating System**: Windows 
-   **Package Version**: 4.5.9

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.
