### ISSUE TITLE
relationshipType support; outdated experimental version

### ISSUE THREAD

**Issue by didaktio** [contentful/contentful-migration#998]
It's not currently possible to use the experimental version with the latest features, such as setting `defaultValue`.

## Expected Behavior

Using contentful-migration@experimental allows `relationshipType` validations to be set when using more recent additions like defaultValue. 

## Actual Behavior

`A field can't have "relationshipType" as a validation.` OR `"defaultValue" is not a valid property name for a field.`

## Possible Solution

Update experimental version. But at first glance this might not work because the contentful-cli@experimental is also outdated.

**Comment by dustinbrownman** [comment]
+1 to this. I opened a similar issue on the Contentful CLI project: https://github.com/contentful/contentful-cli/issues/1332

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.
